export interface LocationItem {
    id: string;
    name: string;
    province: string;
    type: 'province' | 'municipality';
}

export const LOCATIONS: LocationItem[] = [
    // PROVINCES
    { id: "01", name: "Álava", province: "Álava", type: "province" },
    { id: "02", name: "Albacete", province: "Albacete", type: "province" },
    { id: "03", name: "Alicante", province: "Alicante", type: "province" },
    { id: "04", name: "Almería", province: "Almería", type: "province" },
    { id: "33", name: "Asturias", province: "Asturias", type: "province" },
    { id: "05", name: "Ávila", province: "Ávila", type: "province" },
    { id: "06", name: "Badajoz", province: "Badajoz", type: "province" },
    { id: "07", name: "Baleares", province: "Baleares", type: "province" },
    { id: "08", name: "Barcelona", province: "Barcelona", type: "province" },
    { id: "09", name: "Burgos", province: "Burgos", type: "province" },
    { id: "10", name: "Cáceres", province: "Cáceres", type: "province" },
    { id: "11", name: "Cádiz", province: "Cádiz", type: "province" },
    { id: "39", name: "Cantabria", province: "Cantabria", type: "province" },
    { id: "12", name: "Castellón", province: "Castellón", type: "province" },
    { id: "13", name: "Ciudad Real", province: "Ciudad Real", type: "province" },
    { id: "14", name: "Córdoba", province: "Córdoba", type: "province" },
    { id: "16", name: "Cuenca", province: "Cuenca", type: "province" },
    { id: "17", name: "Gerona", province: "Gerona", type: "province" },
    { id: "18", name: "Granada", province: "Granada", type: "province" },
    { id: "19", name: "Guadalajara", province: "Guadalajara", type: "province" },
    { id: "20", name: "Guipúzcoa", province: "Guipúzcoa", type: "province" },
    { id: "21", name: "Huelva", province: "Huelva", type: "province" },
    { id: "22", name: "Huesca", province: "Huesca", type: "province" },
    { id: "23", name: "Jaén", province: "Jaén", type: "province" },
    { id: "15", name: "La Coruña", province: "La Coruña", type: "province" },
    { id: "26", name: "La Rioja", province: "La Rioja", type: "province" },
    { id: "35", name: "Las Palmas", province: "Las Palmas", type: "province" },
    { id: "24", name: "León", province: "León", type: "province" },
    { id: "25", name: "Lérida", province: "Lérida", type: "province" },
    { id: "27", name: "Lugo", province: "Lugo", type: "province" },
    { id: "28", name: "Madrid", province: "Madrid", type: "province" },
    { id: "29", name: "Málaga", province: "Málaga", type: "province" },
    { id: "30", name: "Murcia", province: "Murcia", type: "province" },
    { id: "31", name: "Navarra", province: "Navarra", type: "province" },
    { id: "32", name: "Orense", province: "Orense", type: "province" },
    { id: "34", name: "Palencia", province: "Palencia", type: "province" },
    { id: "36", name: "Pontevedra", province: "Pontevedra", type: "province" },
    { id: "37", name: "Salamanca", province: "Salamanca", type: "province" },
    { id: "40", name: "Segovia", province: "Segovia", type: "province" },
    { id: "41", name: "Sevilla", province: "Sevilla", type: "province" },
    { id: "42", name: "Soria", province: "Soria", type: "province" },
    { id: "43", name: "Tarragona", province: "Tarragona", type: "province" },
    { id: "38", name: "Santa Cruz de Tenerife", province: "Santa Cruz de Tenerife", type: "province" },
    { id: "44", name: "Teruel", province: "Teruel", type: "province" },
    { id: "45", name: "Toledo", province: "Toledo", type: "province" },
    { id: "46", name: "Valencia", province: "Valencia", type: "province" },
    { id: "47", name: "Valladolid", province: "Valladolid", type: "province" },
    { id: "48", name: "Vizcaya", province: "Vizcaya", type: "province" },
    { id: "49", name: "Zamora", province: "Zamora", type: "province" },
    { id: "50", name: "Zaragoza", province: "Zaragoza", type: "province" },
    { id: "51", name: "Ceuta", province: "Ceuta", type: "province" },
    { id: "52", name: "Melilla", province: "Melilla", type: "province" },

    // MUNICIPALITIES (Sample plus requested ones)
    { id: "m1", name: "Astudillo", province: "Palencia", type: "municipality" },
    { id: "m2", name: "Astulez", province: "Álava", type: "municipality" },
    { id: "m3", name: "Astun", province: "Huesca", type: "municipality" },
    { id: "m4", name: "Astureses", province: "Ourense", type: "municipality" },
    { id: "m5", name: "Asturianos", province: "Zamora", type: "municipality" },
    { id: "m6", name: "Lugar Da Asturiana", province: "A Coruña", type: "municipality" },
    { id: "m7", name: "O Outeiro (Astureses)", province: "Ourense", type: "municipality" },
    { id: "m8", name: "Toledo de Asturias", province: "Asturias", type: "municipality" },
    { id: "m9", name: "Vigo de Asturias", province: "Asturias", type: "municipality" },

    // Major cities as municipalities too (common UX)
    { id: "m10", name: "Madrid", province: "Madrid", type: "municipality" },
    { id: "m11", name: "Barcelona", province: "Barcelona", type: "municipality" },
    { id: "m12", name: "Valencia", province: "Valencia", type: "municipality" },
    { id: "m13", name: "Sevilla", province: "Sevilla", type: "municipality" },
    { id: "m14", name: "Zaragoza", province: "Zaragoza", type: "municipality" },
    { id: "m15", name: "Málaga", province: "Málaga", type: "municipality" },
    { id: "m16", name: "Murcia", province: "Murcia", type: "municipality" },
    { id: "m17", name: "Palma de Mallorca", province: "Baleares", type: "municipality" },
    { id: "m18", name: "Las Palmas de Gran Canaria", province: "Las Palmas", type: "municipality" },
    { id: "m19", name: "Bilbao", province: "Vizcaya", type: "municipality" },
    { id: "m20", name: "Alicante", province: "Alicante", type: "municipality" },
    { id: "m21", name: "Córdoba", province: "Córdoba", type: "municipality" },
    { id: "m22", name: "Valladolid", province: "Valladolid", type: "municipality" },
    { id: "m23", name: "Vigo", province: "Pontevedra", type: "municipality" },
    { id: "m24", name: "Gijón", province: "Asturias", type: "municipality" },
    { id: "m25", name: "Oviedo", province: "Asturias", type: "municipality" },
];
