export const NEIGHBORING_PROVINCES: Record<string, string[]> = {
    "A Coruña": ["Lugo", "Pontevedra"],
    "Álava": ["Bizkaia", "Gipuzkoa", "Navarra", "La Rioja", "Burgos"],
    "Albacete": ["Cuenca", "Valencia", "Alicante", "Murcia", "Granada", "Jaén", "Ciudad Real"],
    "Alicante": ["Valencia", "Albacete", "Murcia"],
    "Almería": ["Granada", "Murcia"],
    "Asturias": ["Lugo", "Cantabria", "León"],
    "Ávila": ["Valladolid", "Segovia", "Madrid", "Toledo", "Cáceres", "Salamanca"],
    "Badajoz": ["Cáceres", "Toledo", "Ciudad Real", "Córdoba", "Sevilla", "Huelva"],
    "Baleares": ["Barcelona", "Valencia", "Alicante"], // Not strictly neighbors but closest via sea
    "Barcelona": ["Girona", "Lleida", "Tarragona"],
    "Bizkaia": ["Cantabria", "Burgos", "Álava", "Gipuzkoa"],
    "Burgos": ["Cantabria", "Bizkaia", "Álava", "La Rioja", "Soria", "Segovia", "Valladolid", "Palencia"],
    "Cáceres": ["Salamanca", "Ávila", "Toledo", "Badajoz"],
    "Cádiz": ["Huelva", "Sevilla", "Málaga"],
    "Cantabria": ["Asturias", "Bizkaia", "Burgos", "Palencia", "León"],
    "Castellón": ["Tarragona", "Teruel", "Valencia"],
    "Ciudad Real": ["Toledo", "Cuenca", "Albacete", "Jaén", "Córdoba", "Badajoz"],
    "Córdoba": ["Badajoz", "Ciudad Real", "Jaén", "Granada", "Málaga", "Sevilla"],
    "Cuenca": ["Guadalajara", "Teruel", "Valencia", "Albacete", "Ciudad Real", "Toledo", "Madrid"],
    "Gipuzkoa": ["Bizkaia", "Álava", "Navarra"],
    "Girona": ["Barcelona", "Lleida"],
    "Granada": ["Málaga", "Córdoba", "Jaén", "Albacete", "Murcia", "Almería"],
    "Guadalajara": ["Madrid", "Segovia", "Soria", "Zaragoza", "Teruel", "Cuenca"],
    "Huelva": ["Badajoz", "Sevilla", "Cádiz"],
    "Huesca": ["Navarra", "Zaragoza", "Lleida"],
    "Jaén": ["Ciudad Real", "Albacete", "Granada", "Córdoba"],
    "La Rioja": ["Álava", "Navarra", "Zaragoza", "Soria", "Burgos"],
    "Las Palmas": ["Santa Cruz de Tenerife"],
    "León": ["Asturias", "Cantabria", "Palencia", "Valladolid", "Zamora", "Ourense", "Lugo"],
    "Lleida": ["Girona", "Barcelona", "Tarragona", "Zaragoza", "Huesca"],
    "Lugo": ["A Coruña", "Pontevedra", "Ourense", "León", "Asturias"],
    "Madrid": ["Segovia", "Guadalajara", "Cuenca", "Toledo", "Ávila"],
    "Málaga": ["Cádiz", "Sevilla", "Córdoba", "Granada"],
    "Murcia": ["Alicante", "Albacete", "Granada", "Almería"],
    "Navarra": ["Gipuzkoa", "Álava", "La Rioja", "Zaragoza", "Huesca"],
    "Ourense": ["Pontevedra", "Lugo", "León", "Zamora"],
    "Palencia": ["Cantabria", "Burgos", "Valladolid", "León"],
    "Pontevedra": ["A Coruña", "Lugo", "Ourense"],
    "Salamanca": ["Zamora", "Valladolid", "Ávila", "Cáceres"],
    "Santa Cruz de Tenerife": ["Las Palmas"],
    "Segovia": ["Valladolid", "Burgos", "Soria", "Guadalajara", "Madrid", "Ávila"],
    "Sevilla": ["Huelva", "Badajoz", "Córdoba", "Málaga", "Cádiz"],
    "Soria": ["La Rioja", "Zaragoza", "Guadalajara", "Segovia", "Burgos"],
    "Tarragona": ["Barcelona", "Lleida", "Zaragoza", "Teruel", "Castellón"],
    "Teruel": ["Zaragoza", "Tarragona", "Castellón", "Valencia", "Cuenca", "Guadalajara"],
    "Toledo": ["Madrid", "Cuenca", "Ciudad Real", "Badajoz", "Cáceres", "Ávila"],
    "Valencia": ["Castellón", "Teruel", "Cuenca", "Albacete", "Alicante"],
    "Valladolid": ["León", "Palencia", "Burgos", "Segovia", "Ávila", "Salamanca", "Zamora"],
    "Zamora": ["Ourense", "León", "Valladolid", "Salamanca"],
    "Zaragoza": ["Huesca", "Lleida", "Tarragona", "Teruel", "Guadalajara", "Soria", "La Rioja", "Navarra"]
};
