export const PREDEFINED_TAGS: Record<string, string[]> = {
  // GANADERÍA
  bovino: [
    "vacas lecheras", "vacas de carne", "vacas nodrizas", "vacas de cría", 
    "vacas preñadas", "vacas paridas", "vacas recién paridas", "vacas secas", 
    "vacas de ordeño", "vacuno de cebo", "terneros de cebo", "terneros lechales", 
    "terneros mamones", "terneros paseros", "terneras", "novillos", "novillas", 
    "añojos", "chotos", "erales", "utreros", "cuatreños", "becerros", "becerras", 
    "recentales", "sementales", "toro semental", "toro de lidia", "toro bravo", 
    "lote de vacas", "ganado vacuno", "frisona", "holstein", "jersey", "pardo suizo", 
    "pardo alpina", "ayrshire", "rubia gallega", "asturiana de los valles", 
    "asturiana de la montaña", "avileña negra ibérica", "pirenaica", "retinta", 
    "morucha", "tudanca", "parda de montaña", "monchina", "pasiega", "sayaguesa", 
    "serrana de teruel", "palmera", "mostrenca", "marismeña", "berrenda en negro", 
    "berrenda en colorado", "cachena", "caldelana", "frieiresa", "limiá", "menorquina", 
    "mallorquina", "pajuna", "terreña", "cárdena andaluza", "charolais", "limusín", 
    "limousine", "angus", "black angus", "hereford", "simmental", "blonde de aquitania", 
    "salers", "wagyu", "blanco azul belga", "belgian blue", "aubrac", "galloway", 
    "venta de vacas segunda mano", "vacas baratas", "vacas con cuota"
  ],
  equino: [
    "caballos", "yeguas", "potros", "potras", "potrillos", "sementales equinos", 
    "caballos capados", "caballos enteros", "caballos de doma", "caballos de salto", 
    "caballos de paseo", "caballos de trabajo", "caballos de tiro", "caballos trotadores", 
    "caballos para iniciación", "caballos escolares", "caballos para niños", 
    "pura raza española", "PRE", "caballo andaluz", "lusitano", "hispano-árabe", 
    "hispano-bretón", "pura sangre árabe", "pura sangre inglés", "PSI", "cuarto de milla", 
    "appaloosa", "frisón", "anglo-árabe", "burguete", "jaca navarra", "pottoka", "losino", 
    "asturcón", "gallego de monte", "pura raza gallega", "mallorquín", "menorquín", 
    "marismeño equino", "monchino equino", "doma clásica", "doma vaquera", 
    "salto de obstáculos", "raid", "completo", "enganches", "alta escuela", 
    "yegua preñada", "yegua parida", "potro lechal", "potro destetado", "burro andaluz", 
    "asno catalán", "burro zamorano-leonés", "burro de las encartaciones", "burro majorero", 
    "burro balear", "mulas", "mulos", "venta caballos", "compra caballos", 
    "caballo segunda mano", "alquiler caballo", "regalo caballo", "adopción caballo"
  ],
  caprino: [
    "cabras", "machos cabríos", "chivos", "chivas", "chivitos", "cabritos", 
    "cabritos lechales", "cabritos segureños", "choto", "choto segureño", 
    "recentales caprinos", "cabras lecheras", "cabras de carne", "cabras de leche", 
    "cabras preñadas", "rebaño de cabras", "lote de cabras", "ganadería caprina", 
    "granja caprina", "murciano-granadina", "malagueña", "florida", "payoya", 
    "tinerfeña", "palmera caprina", "majorera", "verata", "retinta extremeña", 
    "negra serrana", "blanca andaluza", "blanca celtibérica", "pirenaica", "bermeya", 
    "azpi gorri", "moncaina", "mallorquina caprina", "ibicenca", "guadarrama", 
    "agrupación de las mesetas", "galega caprina", "alpina", "saanen", "anglo-nubia", 
    "boer", "toggenburg", "cabra enana", "cabra de pet", "semental caprino", 
    "ordeño cabras", "leche de cabra", "queso de cabra", "cabra ecológica", 
    "cabra extensiva", "venta cabras segunda mano", "cabras baratas", "lote chivos engorde", 
    "cabra de teta"
  ],
  ovino: [
    "ovejas", "corderos", "corderos lechales", "corderos pascuales", "corderos recentales", 
    "ternasco", "ternasco de aragón", "lechazo", "borregos", "borregas", "primalas", 
    "andoscas", "moruecos", "carneros", "sementales ovinos", "ovejas preñadas", 
    "ovejas paridas", "ovejas lecheras", "ovejas de carne", "ovejas madre", "rebaño de ovejas", 
    "lote de ovejas", "ganadería ovina", "pastoreo", "trashumancia", "merina", "merina negra", 
    "merina precoz", "manchega", "manchega negra", "manchega lechera", "castellana", 
    "castellana negra", "churra", "churra lebrijana", "rasa aragonesa", "navarra", "latxa", 
    "lacha cara rubia", "lacha cara negra", "carranzana", "sasi ardi", "ojinegra de teruel", 
    "maellana", "roya bilbilitana", "cartera", "ansotana", "chamarita", "xisqueta", 
    "ripollesa", "aranesa", "tarasconesa", "talaverana", "alcarreña", "segureña", 
    "ojalada soriana", "assaf", "awassi", "lacaune", "berrichon", "ile de france", "texel", 
    "suffolk", "frisona ovina", "venta ovejas segunda mano", "ovejas baratas", 
    "lote corderos engorde", "ovejas con cordero al pie"
  ],
  porcino: [
    "cerdos", "cerdos ibéricos", "cerdo blanco", "cerdo de cebo", "cerdo de bellota", 
    "cerdo de campo", "lechones", "cochinillos", "cebones", "gorrinos", "marranos", 
    "guarros", "cochos", "verraco", "semental porcino", "cerda madre", "cerda reproductora", 
    "cerdas preñadas", "cerdas primerizas", "ibérico puro", "ibérico 100%", "ibérico 75%", 
    "ibérico 50%", "ibérico de bellota", "ibérico cebo", "ibérico cebo de campo", "duroc", 
    "cruce duroc", "pietrain", "landrace", "large white", "yorkshire", "mangalica", 
    "chato murciano", "negra mallorquina", "porc negre mallorquí", "negro canario", 
    "celta", "euskal txerria", "lermeño", "jabalí", "cruce jabalí", "jabalí domesticado", 
    "montanera", "dehesa", "cebadero porcino", "granja porcina", "cerdos para sacrificio", 
    "cerdos engorde", "granja ibérica", "lote lechones", "lote cochinillos", "ibérico de montanera", 
    "ibérico recebo", "venta cerdos segunda mano", "cerdos baratos", "padrillos ibéricos", 
    "primalas ibéricas", "transición porcino", "destete porcino"
  ],
  avicultura: [
    "gallinas", "gallinas ponedoras", "gallinas camperas", "gallinas ecológicas", 
    "gallinas reproductoras", "gallos", "capones", "pollos", "pollos broiler", 
    "pollos de corral", "pollos camperos", "pollos ecológicos", "pollitos", 
    "pollitos un día", "pollitos recién nacidos", "pavos", "pavas", "patos", "ánades", 
    "ocas", "gansos", "codornices", "codornices ponedoras", "faisanes", "perdices", 
    "perdiz roja", "palomas", "pichones", "gallinas guinea", "pintadas", "huevos fértiles", 
    "incubadora", "criadero", "castellana negra", "andaluza azul", "andaluza sureña", 
    "penedesenca", "empordanesa", "prat", "sureña", "vasca", "euskal oiloa", "mallorquina", 
    "menorquina aves", "pita pinta asturiana", "murciana", "valenciana de chulilla", 
    "utrerana", "pardilla de sigüenza", "buff orpington", "sussex", "plymouth rock", 
    "brahma", "cochinchina", "rhode island", "leghorn", "marans", "araucana", "sebright", 
    "wyandotte", "padovana", "sedosa japonesa", "gallos ornamentales", "gallinas ornamentales", 
    "lote ponedoras", "venta gallinas segunda puesta", "gallinas para asar", "pollos al corte", 
    "granja avícola"
  ],
  apicultura: [
    "abejas", "colmenas", "núcleos de abejas", "enjambres", "reinas de abeja", 
    "abejas reina", "abeja ibérica", "abeja negra", "abeja italiana", "ligustica", 
    "abeja carniola", "colmena langstroth", "colmena layens", "colmena dadant", 
    "colmena warré", "colmena horizontal", "colmena vertical", "núcleo de fecundación", 
    "cuadros colmena", "alzas", "melarios", "cámara de cría", "fundación de cera", 
    "cera estampada", "miel", "miel artesanal", "miel ecológica", "miel del país", 
    "miel cruda", "miel de mil flores", "miel de azahar", "miel de romero", "miel de tomillo", 
    "miel de brezo", "miel de encina", "miel de roble", "miel de eucalipto", "polen", 
    "propóleo", "jalea real", "panales", "cera de abejas", "ahumador", "traje de apicultor", 
    "mascarilla apicultor", "extractor de miel", "banco desopercular", "desoperculadora", 
    "madurador", "decantador", "espátula", "palanca apicultor", "cepillo abejas", 
    "alimentador", "trampa de polen", "excluidor de reinas", "apiario", "colmenar", 
    "venta colmenas pobladas", "venta enjambres trashumancia", "venta reinas fecundadas"
  ],
  perros: [
    "mastín español", "mastín del pirineo", "mastín leonés", "carea leonés", 
    "carea castellano manchego", "pastor garafiano", "pastor vasco", "iletsoa", 
    "gorbeiakoa", "ca de bestiar", "pastor mallorquín", "gos d'atura català", 
    "pastor belga malinois", "pastor belga tervueren", "pastor alemán", "border collie", 
    "kelpie australiano", "pastor australiano", "perro guardián", "perro pastor", 
    "perro de rehala", "perro de jabalí", "perro presa", "podenco andaluz", 
    "podenco ibicenco", "podenco canario", "podenco maneto", "podenco orito", 
    "podenco portugués", "podenco valenciano", "galgo español", "sabueso español", 
    "pachón navarro", "perdiguero de burgos", "perdiguero mallorquín", 
    "ratonero bodeguero andaluz", "ratonero valenciano", "ratonero murciano", 
    "ratonero mallorquín", "setter inglés", "setter irlandés", "pointer", 
    "bracco italiano", "spaniel bretón", "cocker spaniel", "springer spaniel", 
    "alano español", "bulldog español", "presa canario", "ca de bou", 
    "villano de las encartaciones", "perro de agua español", "cachorros con pedigree", 
    "cachorros sin pedigree", "venta cachorros", "camada", "regalo cachorros", 
    "adopción cachorros", "perro adiestrado caza", "perro adiestrado pastor", 
    "perro joven", "perro adulto", "perro reproductor"
  ],
  conejos: [
    "conejos", "gazapos", "conejillos", "conejos engorde", "conejo reproductor", 
    "conejo madre", "conejo padre", "conejo macho", "conejo hembra", "conejo cría", 
    "conejo de granja", "conejo de carne", "conejo ornamental", "conejo pet", 
    "conejo enano", "conejo doméstico", "neozelandés blanco", "californiano", 
    "gigante de españa", "gigante pardo de españa", "gigante de flandes", "belier", 
    "mariposa enano", "cabeza de león", "angora", "rex", "rex castor", "holandés", 
    "mini lop", "chinchilla", "plateado de champagne", "mariposa español", 
    "hotot enano", "tan", "habanero", "lebrel", "lote de gazapos", "lote de conejos engorde", 
    "jaulas para conejos", "conejera", "granja de conejos", "paridera conejo", 
    "comedero conejo", "bebedero conejo", "nido conejo", "piel de conejo", 
    "carne de conejo", "conejo ecológico", "conejo casero", "venta conejos segunda mano", 
    "regalo conejos", "adopción conejos", "conejo de exposición", "conejo cunícola"
  ],
  otros: [
    "llamas", "alpacas", "avestruces", "emús", "ñandú", "búfalos", "búfalo de agua", 
    "ciervos", "gamos", "muflones", "jabalí domesticado", "helicicultura", "caracoles", 
    "peces", "truchas", "esturiones", "tilapia", "anguilas", "carpas", "doradas", 
    "lubinas", "pavos reales", "faisanes ornamentales", "aves exóticas", "loros", 
    "agapornis", "ninfas", "cacatúas", "reptiles", "tortugas", "iguanas", "hurones", 
    "chinchillas", "cobayas", "cobaya peruano", "ratones", "ratas", "hámster", 
    "cobayas exóticas", "ranas", "hormigas", "escarabajos", "grillos", "gusanos de seda", 
    "lombrices", "vermicompostaje", "gusanos tenebrios", "perdices reales", 
    "codornices ornamentales", "faisán dorado", "cisnes", "patos ornamentales", 
    "granja didáctica", "animales granja escuela", "animales de compañía rural", 
    "fauna autóctona"
  ],
  
  // MAQUINARIA Y HERRAMIENTAS
  tractores: [
    "tractor agrícola", "tractor frutero", "tractor viñero", "tractor estrecho", 
    "tractor articulado", "tractor de oruga", "tractor de cadenas", "tractor compacto", 
    "mini tractor", "tractor 4x4", "tractor doble tracción", "tractor simple tracción", 
    "tractor con pala", "tractor con remolque", "tractor con cabina", "tractor sin cabina", 
    "tractor con arco de seguridad", "tractor 50 cv", "tractor 80 cv", "tractor 100 cv", 
    "tractor 150 cv", "tractor 200 cv", "tractor matriculado", "tractor con ITV", 
    "john deere", "new holland", "case ih", "massey ferguson", "kubota", "fendt", 
    "claas", "deutz-fahr", "same", "landini", "mccormick", "valtra", "lamborghini trattori", 
    "goldoni", "ebro", "pasquali", "bcs", "lindner", "jcb", "antonio carraro", 
    "ferrari tractor", "yanmar", "iseki", "carraro", "tractor segunda mano", 
    "tractor ocasión", "tractor usado", "tractor barato", "tractor antiguo", 
    "tractor restaurado", "tractor para reparar", "tractor para piezas", 
    "repuestos tractor", "ruedas tractor", "neumáticos agrícolas", "lastres tractor", 
    "contrapesos", "pala cargadora tractor", "pala frontal", "elevador trasero", 
    "elevador delantero", "toma de fuerza", "alquiler tractor", "venta tractor particular"
  ],
  abonadoras: [
    "abonadora centrífuga", "abonadora pendular", "abonadora suspendida", 
    "abonadora arrastrada", "abonadora doble disco", "abonadora simple disco", 
    "abonadora neumática", "abonadora hidráulica", "abonadora purín", 
    "abonadora estiércol", "abonadora sólido", "abonadora líquido", 
    "esparcidor de estiércol", "esparcidor universal", "cuba de purín", 
    "cuba esparcidora", "remolque abonadora", "abonadora 500 litros", 
    "abonadora 1000 litros", "abonadora 1500 litros", "abonadora 2000 litros", 
    "abonadora 3000 litros", "abonadora para abono granulado", "abonadora para urea", 
    "abonadora para purines", "abonadora para gallinaza", "abonadora para compost", 
    "abonadora para sal", "vicon", "sulky", "amazone", "kuhn", "bogballe", "aguirre", 
    "solá", "rauch", "bredal", "lely", "gascón", "cuypers", "joskin", "ovlac", "pichon", 
    "samasz", "abonadora segunda mano", "abonadora ocasión", "abonadora nueva", 
    "abonadora barata", "abonadora restaurada", "venta abonadora", "alquiler abonadora", 
    "abonadora particular", "abonadora con regulador hidráulico", "abonadora con caja inox", 
    "abonadora doble plato", "abonadora ancho variable", "abonadora 12 metros", 
    "abonadora 18 metros", "abonadora 24 metros", "abonadora para olivar", 
    "abonadora con sinfín", "abonadora a voleo"
  ],
  cosechadoras: [
    "cosechadora de cereal", "cosechadora de maíz", "cosechadora de arroz", 
    "cosechadora de girasol", "cosechadora oleaginosas", "cosechadora forraje", 
    "cosechadora remolacha", "cosechadora patata", "cosechadora aceituna", 
    "cosechadora uva", "vendimiadora", "cosechadora frutos secos", 
    "cosechadora almendras", "cosechadora pistacho", "cosechadora oruga", 
    "cosechadora ruedas", "cosechadora rotativa", "cosechadora axial", 
    "cosechadora sacudidores", "cosechadora doble rotor", "john deere cosechadora", 
    "claas cosechadora", "new holland cosechadora", "case ih cosechadora", 
    "massey ferguson cosechadora", "deutz-fahr cosechadora", "fendt cosechadora", 
    "laverda", "sampo", "rostselmash", "cabezal cosechadora", "plataforma de corte", 
    "molinete", "sinfín cosechadora", "picador cosechadora", "despajador", 
    "tolva grano", "tubo de descarga", "cabezal maíz", "cabezal girasol", 
    "cabezal cereal flexible", "cabezal cereal rígido", "cosechadora segunda mano", 
    "cosechadora ocasión", "cosechadora antigua", "cosechadora barata", 
    "cosechadora particular", "venta cosechadora", "alquiler cosechadora", 
    "cosechadora para servicio", "servicio cosechadora", "cosechadora con GPS", 
    "cosechadora con piloto automático", "repuestos cosechadora"
  ],
  desbrozadoras: [
    "desbrozadora frontal", "desbrozadora trasera", "desbrozadora lateral", 
    "desbrozadora brazo articulado", "desbrozadora hidráulica", "desbrozadora forestal", 
    "desbrozadora de martillos", "desbrozadora de cuchillas", "desbrozadora de cadenas", 
    "desbrozadora de hilo", "desbrozadora de gasolina", "desbrozadora eléctrica", 
    "desbrozadora a batería", "desbrozadora mochila", "desbrozadora con ruedas", 
    "desbrozadora manual", "desbrozadora arrastrada", "desbrozadora suspendida", 
    "desbrozadora 1 metro", "desbrozadora 1.20", "desbrozadora 1.50", 
    "desbrozadora 1.80", "desbrozadora 2 metros", "desbrozadora 2.40", 
    "desbrozadora 3 metros", "stihl", "husqvarna", "echo", "honda", "kawasaki", 
    "maruyama", "solo", "oleo-mac", "efco", "cifarelli", "berti", "maschio", 
    "bomford", "ferri", "tierre", "agric", "agrator", "ortolan", "nobili", "seppi", 
    "desbrozar fincas", "desbrozar olivar", "desbrozar viña", "desbrozar pastos", 
    "limpieza forestal", "mantenimiento caminos rurales", "desbrozadora segunda mano", 
    "desbrozadora ocasión", "desbrozadora barata", "venta desbrozadora", 
    "alquiler desbrozadora", "desbrozadora articulada", "desbrozadora con desplazamiento", 
    "desbrozadora reversible", "repuestos desbrozadora", "cuchillas desbrozadora"
  ],
  encintadoras: [
    "encintadora de pacas", "encintadora de pacas redondas", 
    "encintadora de pacas cuadradas", "encintadora individual", "encintadora continua", 
    "encintadora plataforma", "encintadora arrastrada", "encintadora suspendida", 
    "encintadora autocargante", "encintadora hidráulica", "encintadora estática", 
    "encintadora dinámica", "combinada empacadora encintadora", "mchale", 
    "kuhn encintadora", "goweil", "tanco", "krone encintadora", "lely encintadora", 
    "fella", "vicon encintadora", "wolagri", "elho", "tubeline", "anderson", 
    "plástico encintar", "film de silaje", "film paca redonda", "film paca cuadrada", 
    "plástico 750mm", "plástico 500mm", "ensilado en pacas", "henolaje", 
    "prehenificado", "pacas ensiladas", "encintadora segunda mano", "encintadora ocasión", 
    "encintadora nueva", "encintadora barata", "encintadora restaurada", 
    "alquiler encintadora", "venta encintadora", "encintadora particular", 
    "encintadora con autoalimentación", "encintadora doble plataforma", 
    "encintadora trasera", "encintadora telecargada", "brazo giratorio encintadora", 
    "repuestos encintadora", "rodillos encintadora", "encintar pacas servicio", 
    "servicio encintado"
  ],
  empacadoras: [
    "empacadora paca pequeña", "empacadora paca redonda", "empacadora paca cuadrada", 
    "empacadora gran paca", "empacadora alta densidad", "empacadora baja densidad", 
    "empacadora cámara fija", "empacadora cámara variable", "empacadora de rotor", 
    "empacadora con pickup", "empacadora con hilo", "empacadora con red", 
    "empacadora con malla", "empacadora autocargante", "empacadora arrastrada", 
    "combinada empacadora encintadora", "paca redonda 1.20", "paca redonda 1.50", 
    "paca cuadrada 80x90", "paca cuadrada 120x70", "paca cuadrada 120x90", 
    "new holland empacadora", "john deere empacadora", "claas empacadora", 
    "kuhn empacadora", "krone empacadora", "vicon empacadora", "welger", 
    "massey ferguson empacadora", "mchale empacadora", "case ih empacadora", 
    "fendt empacadora", "pottinger", "deutz-fahr empacadora", "hesston", 
    "paca de paja", "paca de alfalfa", "paca de heno", "paca de veza", 
    "paca de cereal", "paca de forraje", "paca de ensilado", "empacadora segunda mano", 
    "empacadora ocasión", "empacadora barata", "empacadora antigua", 
    "empacadora restaurada", "empacadora pequeña", "venta empacadora", 
    "alquiler empacadora", "servicio empacar", "repuestos empacadora", "rotor empacadora"
  ],
  motocultores: [
    "motocultor agrícola", "motocultor para huerta", "motocultor diesel", 
    "motocultor gasolina", "motocultor profesional", "motocultor hortelano", 
    "motocultor pequeño", "mini motocultor", "motocultor con fresa", 
    "motocultor con remolque", "motocultor con arado", "motocultor reversible", 
    "motocultor 4 tiempos", "motocultor 2 tiempos", "motoazada", "motoazada eléctrica", 
    "motoazada gasolina", "motoazada profesional", "mulero", "motocultor 5 cv", 
    "motocultor 7 cv", "motocultor 9 cv", "motocultor 11 cv", "motocultor 13 cv", 
    "motocultor 15 cv", "motocultor 18 cv", "bcs motocultor", "pasquali", "goldoni", 
    "honda motocultor", "yanmar motocultor", "kubota motocultor", "ferrari motocultor", 
    "grillo", "eurosystems", "powerground", "tracmaster", "benassi", "garland", 
    "husqvarna motoazada", "accesorios motocultor", "fresa motocultor", "arado motocultor", 
    "surcador motocultor", "asurcador", "remolque motocultor", "segadora motocultor", 
    "cortacésped motocultor", "escarificador motocultor", "motocultor segunda mano", 
    "motocultor ocasión", "motocultor barato", "motocultor antiguo", "motocultor restaurado", 
    "venta motocultor", "repuestos motocultor", "motocultor particular"
  ],
  remolques: [
    "remolque agrícola", "remolque basculante", "remolque bañera", 
    "remolque caja abierta", "remolque caja cerrada", "remolque ganadero", 
    "remolque transporte ganado", "remolque caballos", "remolque para caballos un solo eje", 
    "remolque cisterna", "remolque cuba", "remolque forrajero", "remolque autocargador", 
    "remolque autocargante", "remolque pulpos", "remolque distribuidor", 
    "remolque tándem", "remolque triéje", "remolque eje simple", "remolque eje tándem", 
    "remolque 3000 kg", "remolque 5000 kg", "remolque 8000 kg", "remolque 12000 kg", 
    "remolque 16000 kg", "remolque 20000 kg", "basculante hidráulico", 
    "basculante manual", "basculante trilateral", "neumáticos agrícolas", 
    "ejes rígidos", "ejes direccionales", "joskin", "carruxo", "bossini", 
    "annaburger", "crosetto", "pichon remolque", "galucho", "rolland", "vaia", 
    "cynkomet", "pronar", "cargo", "conde", "camara", "llopis", "eurotrailer", 
    "galisteo", "brimont", "remolque segunda mano", "remolque ocasión", 
    "remolque barato", "remolque homologado", "remolque matriculado", "venta remolque", 
    "alquiler remolque", "remolque viejo", "remolque restaurado", "remolque para tractor", 
    "remolque con freno hidráulico"
  ],
  sembradoras: [
    "sembradora de cereal", "sembradora de maíz", "sembradora monograno", 
    "sembradora de precisión", "sembradora directa", "sembradora siembra directa", 
    "sembradora convencional", "sembradora neumática", "sembradora mecánica", 
    "sembradora suspendida", "sembradora arrastrada", "sembradora combinada", 
    "sembradora-abonadora", "sembradora hortícola", "sembradora de patatas", 
    "sembradora de ajos", "sembradora rápida", "sembradora a líneas", 
    "sembradora a voleo", "sembradora monograno 4 cuerpos", 
    "sembradora monograno 6 cuerpos", "sembradora monograno 8 cuerpos", 
    "sembradora 3 metros", "sembradora 4 metros", "sembradora 5 metros", 
    "sembradora 6 metros", "sembradora 8 metros", "solá sembradora", "gaspardo", 
    "kuhn sembradora", "amazone sembradora", "lemken", "horsch", "vaderstad", 
    "pottinger sembradora", "sulky sembradora", "monosem", "maschio sembradora", 
    "aguirre sembradora", "urbón", "wintersteiger", "john deere sembradora", 
    "kverneland", "sky sembradora", "sembradora segunda mano", "sembradora ocasión", 
    "sembradora barata", "venta sembradora", "alquiler sembradora", "sembradora antigua", 
    "sembradora restaurada", "sembradora para tractor pequeño", "semillas para sembradora", 
    "repuestos sembradora", "sembradora a chorrillo", "sembradora con micro"
  ],
  sulfatadoras: [
    "sulfatadora arrastrada", "sulfatadora suspendida", "sulfatadora autopropulsada", 
    "sulfatadora mochila", "sulfatadora atomizador", "atomizador tractor", 
    "atomizador para viña", "atomizador para olivar", "atomizador para frutales", 
    "sulfatadora cabezal de niebla", "sulfatadora barras", "sulfatadora hidráulica", 
    "sulfatadora eléctrica", "sulfatadora gasolina", "sulfatadora cisterna", 
    "sulfatadora 200 litros", "sulfatadora 400 litros", "sulfatadora 600 litros", 
    "sulfatadora 1000 litros", "sulfatadora 1500 litros", "sulfatadora 2000 litros", 
    "sulfatadora 3000 litros", "sulfatadora 4000 litros", "hardi", "aguirre sulfatadora", 
    "caffini", "berthoud", "calvet", "fede", "albuz", "lochmann", "pulverizadores fede", 
    "john deere sulfatadora", "amazone sulfatadora", "kverneland sulfatadora", 
    "tecnoma", "kuhn sulfatadora", "iris", "cima", "atomizadores mañez y lozano", 
    "mañez", "boquillas pulverizador", "brazos sulfatadora", "mangueras pulverizador", 
    "regulador presión", "pulverizador", "agitador", "tratamientos fitosanitarios", 
    "herbicidas", "fungicidas", "insecticidas", "sulfatar viña", "sulfatar olivar", 
    "sulfatar cereales", "sulfatar frutales", "sulfatadora segunda mano", 
    "sulfatadora ocasión", "sulfatadora barata", "venta sulfatadora", 
    "atomizador segunda mano", "sulfatadora particular"
  ],
  segadoras: [
    "segadora rotativa", "segadora de discos", "segadora de tambores", 
    "segadora acondicionadora", "acondicionador de rodillos", "acondicionador de mayales", 
    "segadora frontal", "segadora trasera", "segadora lateral", "segadora arrastrada", 
    "segadora suspendida", "segadora reciprocante", "segadora barra de siega", 
    "segadora autopropulsada", "motosegadora", "segadora autocargante", 
    "segadora con sinfín", "segadora con cinta agrupadora", "segadora plegable", 
    "segadora 1.65", "segadora 1.85", "segadora 2 metros", "segadora 2.40", 
    "segadora 2.80", "segadora 3 metros", "segadora 4 metros", "segadora doble", 
    "segadora combinada", "pottinger segadora", "kuhn segadora", "vicon segadora", 
    "krone segadora", "claas segadora", "fella segadora", "lely segadora", 
    "bcs segadora", "galfre", "sip", "sitrex", "wolagri segadora", "deutz-fahr segadora", 
    "siega de alfalfa", "siega de ray-grass", "siega de pradera", "siega de cereal", 
    "siega de forraje", "siega de veza", "segadora segunda mano", "segadora ocasión", 
    "segadora barata", "segadora antigua", "segadora restaurada", "venta segadora", 
    "alquiler segadora", "repuestos segadora", "cuchillas segadora", "segadora para servicio"
  ],
  trituradoras: [
    "trituradora de restos de poda", "trituradora de ramas", "trituradora forestal", 
    "trituradora de martillos", "trituradora de cuchillas", "trituradora hidráulica", 
    "trituradora de cadenas", "trituradora frontal", "trituradora trasera", 
    "trituradora lateral", "trituradora para viñas", "trituradora para olivar", 
    "trituradora para frutales", "trituradora de restos", "trituradora de hierba", 
    "trituradora de pasto", "trituradora caminos", "trituradora arrastrada", 
    "trituradora suspendida", "biotrituradora", "biotrituradora gasolina", 
    "biotrituradora eléctrica", "trituradora con desplazamiento", "trituradora reversible", 
    "trituradora con rodillo", "berti trituradora", "maschio trituradora", 
    "ferri trituradora", "bomford trituradora", "agric trituradora", "tierre trituradora", 
    "ortolan trituradora", "agrator", "seppi", "nobili", "falc", "sicma", 
    "kuhn trituradora", "becchio mandrile", "bandini", "aguirre trituradora", "vigolo", 
    "trituradora 1.40", "trituradora 1.60", "trituradora 1.80", "trituradora 2 metros", 
    "trituradora 2.50", "trituradora 3 metros", "triturar restos poda", 
    "triturar sarmientos", "triturar pastos", "trituradora segunda mano", 
    "trituradora ocasión", "trituradora barata", "venta trituradora", "alquiler trituradora", 
    "martillos trituradora", "repuestos trituradora"
  ],
  volteadoras: [
    "volteadora de forraje", "volteadora de hilera", "volteador rastrillo", 
    "rastrillo hilerador", "hilerador rotativo", "rastrillo de soles", "rastrillo sol", 
    "hilerador de estrellas", "volteadora rotativa", "volteador de heno", 
    "volteador de alfalfa", "volteador hidráulico", "volteadora de compost", 
    "volteadora de estiércol", "volteadora arrastrada", "volteadora suspendida", 
    "volteador 4 soles", "volteador 6 soles", "volteador 8 soles", "hilerador doble", 
    "hilerador simple", "hilerador central", "hilerador lateral", "rastrillo doble", 
    "rastrillo lateral", "volteadora 4 metros", "volteadora 5 metros", "volteadora 6 metros", 
    "volteadora 7 metros", "volteadora 8 metros", "pottinger volteador", "kuhn volteador", 
    "krone volteador", "fella volteador", "vicon volteador", "galfre volteador", 
    "sip volteador", "sitrex volteador", "lely volteador", "stoll", "volteadora segunda mano", 
    "volteadora ocasión", "volteadora barata", "venta volteadora", "rastrillo segunda mano", 
    "hilerador segunda mano", "hilerador en V", "hilerador en línea", "rastrillo de banderas", 
    "volteador plegable", "volteador hidráulico plegable", "volteador para servicio", 
    "voltear pacas", "ahuecador", "repuestos volteador", "voltear forraje pradera"
  ],
  "otra maquinaria agrícola": [
    "arado romano", "arado de vertedera", "arado chisel", "arado reversible", 
    "arado bisurco", "arado trisurco", "arado cuatrisurco", "vibrocultor", "cultivador", 
    "grada de disco", "grada rotativa", "grada vibrante", "subsolador", "rotocultivador", 
    "rotovator", "rulo agrícola", "rodillo agrícola", "rodillo cambridge", "rodillo croskill", 
    "escardadora", "rastra plana", "vibrador de olivas", "paraguas vibrador", 
    "recogedora de aceitunas", "recogedora de almendra", "sacudidor de olivos", 
    "lonas vareo", "vareadores", "peines vareo", "pala cargadora", "manipulador telescópico", 
    "retroexcavadora agrícola", "hormigonera", "generador", "motobomba", "bomba de agua", 
    "bomba sumergible", "gasoil agrícola", "depósito de gasoil", "depósito de agua", 
    "riego por goteo", "riego por aspersión", "aspersores", "programador de riego", 
    "mangueras de riego", "válvulas riego", "filtro riego", "gotero", "cinta exudante", 
    "pivot", "cobertura riego", "mini cargadora", "mini retro", "mini pala", "dumper", 
    "carretilla", "carretilla elevadora", "cintas transportadoras", "elevadores", 
    "secaderos", "silos", "cribadoras", "despedregadoras", "sacudidores", "hidrolimpiadora", 
    "soplador", "motosierra", "podadora", "tijera neumática", "tijera eléctrica", "tijera de poda"
  ],

  // FORRAJE Y ALIMENTACION ANIMAL
  forraje: [
    "paja", "paja de trigo", "paja de cebada", "paja de avena", "paja de centeno", 
    "paja de colza", "heno", "heno de alfalfa", "heno de avena", "heno de veza", 
    "heno de ray-grass", "heno de pradera", "heno de festuca", "heno de dactilo", 
    "ensilado", "ensilado de maíz", "ensilado de hierba", "ensilado de alfalfa", 
    "ensilado de ray-grass", "henolaje", "prehenificado", "alfalfa", "alfalfa en rama", 
    "alfalfa deshidratada", "alfalfa en cubos", "alfalfa granulada", "pellets de alfalfa", 
    "alfalfa en briquetas", "alfalfa en harina", "veza", "veza forraje", "veza grano", 
    "esparceta", "pipirigallo", "zulla", "trébol", "trébol violeta", "trébol blanco", 
    "sorgo forrajero", "sudán", "raygrass", "festuca", "dactilo", "trigo", "trigo blando", 
    "trigo duro", "cebada", "cebada cervecera", "cebada forrajera", "avena", "avena negra", 
    "centeno", "maíz", "maíz grano", "maíz pienso", "triticale", "mijo", "sorgo", "arroz", 
    "espelta", "escanda", "guisante", "guisante forraje", "guisante proteaginoso", 
    "garbanzo pienso", "haba", "habas pienso", "yero", "yeros", "altramuz", "soja", 
    "alubia pienso", "salvado", "salvado de trigo", "harina de cereal", "gluten de maíz", 
    "cascarilla de soja", "cascarilla de algodón", "cascarilla de arroz", "melaza", 
    "pulpa de remolacha", "bagazo cervecero", "pulpa de cítricos", "semilla de algodón", 
    "torta de soja", "torta de girasol", "harina de pescado", "harina de pluma", 
    "pienso vacuno", "pienso ovino", "pienso porcino", "pienso avícola", "pienso ponedoras", 
    "pienso pollos", "pienso conejos", "pienso caballos", "pienso cabras", "pienso ibérico", 
    "pienso ecológico", "pienso compuesto", "pienso starter", "pienso de engorde", 
    "pienso de producción", "pienso de lactancia", "pienso de destete", "pienso de cebo", 
    "núcleo proteico", "corrector vitamínico mineral", "sal mineral", "bloques minerales", 
    "lamedero", "leche de reemplazo", "lactoreemplazante", "paca cuadrada", "paca redonda", 
    "paca grande", "paca pequeña", "mini paca", "big bag", "saco 25 kg", "saco 40 kg", 
    "granel", "a granel", "lote forraje", "pasto", "rastrojo", "dehesa", "rastrojera", 
    "hoja de maíz", "harina de garrofa", "garrofa", "algarroba pienso", "remolacha forrajera", 
    "nabo forrajero", "colza forrajera"
  ],

  // FINCAS
  venta: [
    "finca rústica", "finca agrícola", "finca ganadera", "finca de recreo", 
    "finca cinegética", "finca de caza", "finca olivar", "finca de viña", "finca de cereal", 
    "finca de pastos", "finca de regadío", "finca de secano", "finca con dehesa", 
    "finca de encinar", "finca de alcornocal", "finca de pinar", "finca frutal", 
    "finca de almendros", "finca de cítricos", "finca hortícola", "finca de arrozal", 
    "finca de remolacha", "parcela agrícola", "parcela rústica", "parcela urbanizable", 
    "terreno rústico", "finca con casa", "finca con casa rural", "finca con cortijo", 
    "finca con masía", "finca con caserío", "finca con corrales", "finca con naves", 
    "finca con nave agrícola", "finca con almacén", "finca con bodega", "finca con pozo", 
    "finca con manantial", "finca con balsa", "finca con riego", "finca con luz", 
    "finca con acceso", "finca con permiso de obra", "finca con licencia ganadera", 
    "finca con licencia de hostelería", "finca vallada", "con vallado cinegético", 
    "finca de 1 hectárea", "finca de 5 hectáreas", "finca de 10 hectáreas", 
    "finca de 20 hectáreas", "finca de 50 hectáreas", "finca de 100 hectáreas", 
    "finca grande", "finca pequeña", "microparcela", "finca andalucía", "finca extremadura", 
    "finca castilla", "finca galicia", "finca asturias", "finca cantabria", "venta de finca", 
    "compra finca", "finca barata", "finca particular", "finca de subasta", "finca de embargo", 
    "finca por herencia", "finca de traspaso", "finca de inversión", "finca con derechos PAC", 
    "finca con derechos pago básico"
  ],
  alquiler: [
    "alquiler de finca", "alquiler de finca rústica", "alquiler de tierras", 
    "alquiler de tierras de cultivo", "alquiler de pastos", "alquiler de dehesa", 
    "alquiler de caza", "arrendamiento de finca", "arrendamiento rústico", 
    "alquiler larga duración", "alquiler corta temporada", "alquiler temporal", 
    "alquiler anual", "alquiler de nave agrícola", "alquiler de corrales", 
    "alquiler de establo", "alquiler de cuadras", "alquiler de campa", "alquiler de era", 
    "alquiler de almacén agrícola", "alquiler de invernadero", "alquiler de huerto", 
    "alquiler de huerto urbano", "alquiler de parcela", "alquiler de granja", 
    "alquiler de explotación", "alquiler de colmenar", "alquiler para pastoreo", 
    "alquiler para siega", "alquiler para cereal", "alquiler para viña", 
    "alquiler para olivar", "alquiler para frutales", "alquiler de regadío", 
    "alquiler de secano", "alquiler para ganado vacuno", "alquiler para ganado ovino", 
    "alquiler para caballos", "alquiler cinegético", "alquiler caza mayor", 
    "alquiler caza menor", "alquiler para ojeo", "alquiler para caza con perros", 
    "alquiler 5 hectáreas", "alquiler 10 hectáreas", "alquiler 50 hectáreas", 
    "alquiler 100 hectáreas", "alquiler por euro/hectárea", "alquiler por euros al mes", 
    "alquiler por euros al año", "renta de tierras", "alquiler de finca particular", 
    "busco finca en alquiler", "ofrezco finca en alquiler", "alquiler de gallinero", 
    "alquiler de redil", "alquiler de aprisco", "alquiler de tinada", "contrato arrendamiento rústico"
  ],
  "traspasos explotaciones": [
    "traspaso de explotación", "traspaso de explotación ganadera", "traspaso explotación vacuno", 
    "traspaso explotación ovino", "traspaso explotación caprino", "traspaso explotación porcino", 
    "traspaso explotación lechera", "traspaso explotación cárnica", "traspaso de granja", 
    "traspaso de granja avícola", "traspaso granja porcina", "traspaso granja de conejos", 
    "traspaso de colmenar", "traspaso apiario", "traspaso de bodega", "traspaso de almazara", 
    "traspaso de quesería", "traspaso de ganadería", "traspaso de rebaño", "traspaso lote vacas", 
    "traspaso lote ovejas", "traspaso lote cabras", "traspaso derechos PAC", 
    "traspaso derechos pago básico", "traspaso derechos pago único", "traspaso cuota láctea", 
    "traspaso cuota lechera", "traspaso explotación con derechos", "traspaso explotación con tierras", 
    "traspaso explotación con maquinaria", "traspaso explotación llave en mano", 
    "traspaso negocio agropecuario", "traspaso negocio rural", "traspaso turismo rural", 
    "traspaso casa rural", "traspaso de huerta", "traspaso de invernaderos", "traspaso de vivero", 
    "traspaso de piscifactoría", "traspaso de truchera", "traspaso vacas con cuota", 
    "traspaso explotación con CEA", "traspaso REGA", "traspaso CEA", "traspaso explotación intensiva", 
    "traspaso explotación extensiva", "traspaso explotación ecológica", "jubilación agricultor", 
    "jubilación ganadero", "busco traspaso explotación", "ofrezco traspaso explotación", 
    "relevo generacional", "traspaso por cese", "cese de actividad agraria", "traspaso de cebadero", 
    "traspaso integración", "traspaso de explotación con vivienda"
  ],

  // AGRICULTURA
  semillas: [
    "semilla de trigo", "trigo blando", "trigo duro", "semilla de cebada", "cebada cervecera", 
    "cebada forrajera", "semilla de avena", "avena negra", "avena blanca", "semilla de centeno", 
    "semilla de triticale", "semilla de maíz", "maíz forrajero", "maíz dulce", "maíz grano", 
    "semilla de arroz", "semilla de sorgo", "semilla de mijo", "semilla de espelta", 
    "semilla de escanda", "semilla de veza", "semilla de guisante", "semilla de garbanzo", 
    "semilla de lenteja", "semilla de habas", "semilla de yeros", "semilla de esparceta", 
    "semilla de zulla", "semilla de altramuz", "semilla de soja", "semilla de alubia", 
    "semilla de judía", "semilla de alfalfa", "semilla de trébol", "semilla de ray-grass", 
    "semilla de festuca", "semilla de dactilo", "semilla de pradera", "semilla de césped", 
    "semilla mezcla pradera", "semilla de tomate", "semilla de pimiento", "semilla de pepino", 
    "semilla de calabacín", "semilla de calabaza", "semilla de berenjena", "semilla de lechuga", 
    "semilla de acelga", "semilla de espinaca", "semilla de zanahoria", "semilla de cebolla", 
    "semilla de puerro", "semilla de ajo", "diente de ajo siembra", "semilla de patata", 
    "patata de siembra", "semilla de melón", "semilla de sandía", "semilla de judía verde", 
    "semilla de coliflor", "semilla de brócoli", "semilla de repollo", "semilla de rábano", 
    "semilla de nabo", "semilla de remolacha", "semilla de pepinillo", "semilla de girasol", 
    "semilla de colza", "semilla de cártamo", "semilla de lino", "semilla de albahaca", 
    "semilla de perejil", "semilla de cilantro", "semilla de romero", "semilla de tomillo", 
    "semilla de orégano", "semilla de menta", "semilla de salvia", "semilla ecológica", 
    "semilla bio", "semilla orgánica", "semilla autóctona", "semilla tradicional", 
    "semilla de variedad antigua", "semilla híbrida", "semilla certificada", "semilla R1", 
    "semilla R2", "semilla peletizada", "semilla tratada", "semilla sin tratar", 
    "semillas a granel", "semillas en sobre", "semilleros", "banco de semillas"
  ],
  "plantas y plantones": [
    "planton de manzano", "planton de peral", "planton de cerezo", "planton de melocotonero", 
    "planton de ciruelo", "planton de albaricoquero", "planton de higuera", "planton de membrillero", 
    "planton de nogal", "planton de avellano", "planton de castaño", "planton de kiwi", 
    "planton de granado", "planton de caqui", "planton de aguacate", "planton de mango", 
    "planton de chirimoyo", "planton de naranjo", "planton de mandarino", "planton de limonero", 
    "planton de pomelo", "planton de lima", "planton de olivo", "planton de almendro", 
    "planton de pistacho", "planton de algarrobo", "planton de vid", "planton de parra", 
    "planton de frambuesa", "planton de arándano", "planton de mora", "planton de grosella", 
    "planton de fresa", "planton de fresón", "planton picual", "planton arbequina", 
    "planton hojiblanca", "planton cornicabra", "planton manzanilla", "planton picudo", 
    "planton arbosana", "planton koroneiki", "planton frantoio", "planton tempranillo", 
    "planton garnacha", "planton cabernet", "planton merlot", "planton verdejo", 
    "planton albariño", "planton airén", "planton macabeo", "planton guara almendro", 
    "planton soleta", "planton vairo", "planton lauranne", "planton penta", "planton makako", 
    "planton marta", "planton marcona", "planton largueta", "plantel de tomate", 
    "plantel de pimiento", "plantel de berenjena", "plantel de calabacín", "plantel de pepino", 
    "plantel de lechuga", "plantel de coliflor", "plantel de brócoli", "plantel de repollo", 
    "plantel de acelga", "plantel de cebolla", "plantel de puerro", "plantel de apio", 
    "planton hortícola", "semilleros", "planton de pino", "planton de encina", 
    "planton de alcornoque", "planton de roble", "planton de chopo", "planton de eucalipto", 
    "planton de fresno", "planton de arce", "planton de tilo", "planton autóctono", 
    "planton mediterráneo", "planton injertado", "planton certificado", "planton ecológico", 
    "planton de vivero", "planton raíz desnuda", "planton en contenedor", "planton en bandeja", 
    "planton en maceta", "vivero forestal", "vivero frutal"
  ],

  // SERVICIOS
  "cerramientos y vallados": [
    "cerramiento de finca", "cerramiento ganadero", "cerramiento cinegético", "vallado de caza", 
    "vallado de fincas", "vallado para ganado", "valla pastora", "pastor eléctrico", 
    "vallado eléctrico", "alambrada", "alambre de espino", "malla ganadera", "malla anudada", 
    "malla cinegética", "malla cerramiento", "malla simple torsión", "postes de madera", 
    "postes de hormigón", "postes de acacia", "postes de castaño", "postes metálicos", 
    "puertas de finca", "puerta ganadera", "puerta cancela", "paso canadiense", 
    "instalación de cerramiento", "presupuesto cerramiento", "reparación de vallado", 
    "mantenimiento de vallado", "vallado para caballos", "vallado para vacas", 
    "vallado para ovejas", "vallado para jabalíes", "instalación pastor eléctrico", 
    "batería pastor eléctrico", "panel solar pastor", "hilo eléctrico", "cinta eléctrica", 
    "aislador", "tensor de alambre", "grapas para vallado", "alambre liso", "alambre galvanizado", 
    "cerramiento perimetral", "vallado de madera", "vallado rústico", "valla forestal", 
    "valla autóctona", "presupuesto vallado finca", "vallado de parcela", "vallado para huerto", 
    "vallado para piscina rural", "valla mixta", "cerramiento contra jabalíes", 
    "vallado para colmenar", "vallado para gallinero", "cerramiento de seguridad rural", 
    "cancela rústica", "valla biotop", "cerramiento ecológico", "soldadura de vallas", 
    "malla de simple torsión galvanizada", "malla plastificada"
  ],
  "construcción rural": [
    "construcción de nave agrícola", "nave ganadera", "nave para porcino", "nave avícola", 
    "nave para vacuno", "nave para ovino", "establo", "cuadra", "picadero cubierto", "cobertizo", 
    "almacén agrícola", "garaje agrícola", "henil", "granero", "silo", "depósito de agua", 
    "balsa de riego", "bebedero ganadero", "comedero ganadero", "paridera", "sala de ordeño", 
    "quesería", "almazara", "bodega", "lagar", "secadero de jamón", "secadero de embutidos", 
    "secadero de pimientos", "invernadero", "túnel agrícola", "malla de sombreo", 
    "instalación de riego", "pozos", "sondeos", "perforación de pozo", "hormigonado", 
    "solera de hormigón", "muro de hormigón", "muro de piedra", "muro de mampostería", 
    "refugio de pastor", "cabaña rural", "caseta de aperos", "caseta para perro", "gallinero", 
    "conejera", "palomar", "colmenar", "cubiertas", "tejados", "paneles sándwich", 
    "estructura metálica", "naves prefabricadas", "reformas casa rural", "rehabilitación de cortijo", 
    "restauración de masía", "construcción de cortijo", "construcción de casa rural", 
    "presupuesto construcción rural", "licencia de obra rural", "naves modulares", 
    "casetas prefabricadas", "vivienda modular rural", "vivienda de madera", "casetas para fincas", 
    "taller agrícola", "cebadero", "taller ganadero", "construcción de embalse", "depósito enterrado"
  ],
  esquiladores: [
    "esquilador de ovejas", "esquilador profesional", "esquileo de ovejas", "esquileo tradicional", 
    "esquileo a máquina", "esquileo a tijera", "esquila de lana", "esquila merino", 
    "esquila churra", "esquila lacha", "esquila ovino", "esquila caprino", "esquila cabras", 
    "esquila de llamas", "esquila de alpacas", "esquilador autónomo", "esquilador a domicilio", 
    "esquileo a domicilio", "contratar esquilador", "esquilador zona norte", "esquilador Castilla", 
    "esquilador Aragón", "esquilador Galicia", "esquilador Asturias", "esquilador Extremadura", 
    "esquilador Andalucía", "esquila gran rebaño", "esquila pequeño rebaño", "esquila por cabeza", 
    "precio esquila", "esquila económica", "esquilador con cuadrilla", "cuadrilla de esquileo", 
    "esquila merina", "esquila rasa aragonesa", "esquila precoz", "esquila tardía", 
    "esquileo en primavera", "esquila tradicional manchega", "recogida de lana", 
    "comprador de lana", "venta de lana", "lana esquileo", "esquila ecológica", 
    "esquila bienestar animal", "esquilador con maquinilla", "máquinas de esquilar", 
    "peines y cuchillas", "repuestos esquila", "afilado de peines", "contratar cuadrilla esquileo", 
    "esquila trashumante", "esquilador certificado", "esquila ovino lechero", 
    "esquila ovino cárnico", "lana de oveja sin cardar", "esquila por horas", "esquila completa rebaño"
  ],
  herradores: [
    "herrador de caballos", "herrador profesional", "herrador a domicilio", "herrado de caballos", 
    "herraje de caballos", "herraje en frío", "herraje en caliente", "herraje correctivo", 
    "herraje terapéutico", "herraje deportivo", "herrador titulado", "herrador equino", 
    "herrador de asnos", "herrador de mulas", "herrador de burros", "podólogo equino", 
    "podólogo equino certificado", "recorte de cascos", "recorte de pezuñas", "recorte vaca", 
    "recorte vacuno", "recorte ovejas", "herrado con escayola", "herradura de aluminio", 
    "herradura de acero", "herradura de plástico", "herradura ortopédica", "recorte casco caballo", 
    "mantenimiento de cascos", "salud de cascos", "podología equina", "cuidado de pezuñas", 
    "paneo", "herrador de rehala", "herrador de yeguada", "herrador de picadero", 
    "herrador de hípica", "herrador zona Madrid", "herrador zona Cataluña", "herrador zona Andalucía", 
    "herrador zona Castilla y León", "herrador zona Galicia", "herrador deportivo", 
    "herrador doma clásica", "herrador doma vaquera", "recorte funcional", "recorte alternativo", 
    "herrador descalzo", "barefoot equino", "contratar herrador", "presupuesto herrador", 
    "herrador económico", "herrador para potros", "doma de cascos", "ferraje completo", 
    "cambio de herraduras", "herraje de raza", "recorte de carrera"
  ],
  "mantenimiento de fincas": [
    "mantenimiento de finca", "mantenimiento de finca rústica", "limpieza de fincas", 
    "desbroce de fincas", "desbroce de caminos", "limpieza forestal", "limpieza de cortafuegos", 
    "limpieza de maleza", "poda de olivar", "poda de viña", "poda de frutales", "poda de almendros", 
    "poda ornamental", "poda de formación", "recolección", "recolección de aceituna", "vendimia", 
    "mantenimiento de huerto", "riego programado", "instalación de riego", "reparación de riego", 
    "mantenimiento de maquinaria agrícola", "reparación de tractor", "vaciado de pozos negros", 
    "limpieza de balsa", "limpieza de pozo", "mantenimiento de vallado", "reparación de cerramiento", 
    "control de plagas", "tratamientos fitosanitarios", "sulfatado", "abonado", "siembra", "arado", 
    "gradeado", "encalado", "pavimentación de caminos rurales", "mantenimiento de caminos", 
    "vigilancia de finca", "guardería rural", "cuidado de animales", 
    "alimentación de animales en vacaciones", "paseador de perros", "cuidador de finca", 
    "casero de finca", "presupuesto mantenimiento finca", "contratista agrícola", "servicios agrícolas", 
    "retirada de basura en finca", "tala de árboles", "retirada de árbol caído", "limpieza de canales", 
    "limpieza de acequias", "mantenimiento de jardín rural", "poda de setos", 
    "mantenimiento de césped finca", "recogida de aceituna a maquila", 
    "mantenimiento de olivar tradicional", "mantenimiento de huerta", "mantenimiento de invernaderos"
  ],
  "servicios forestales": [
    "tala de árboles", "tala controlada", "tala forestal", "tala peligrosa", "poda de árboles", 
    "poda en altura", "poda forestal", "trabajos en altura", "trepa de árboles", 
    "podador certificado", "motosierra", "motosierrista", "leñador", "aprovechamiento forestal", 
    "gestión forestal", "plan dasocrático", "repoblación forestal", "plantación forestal", 
    "reforestación", "restauración hidrológica", "lucha contra incendios", 
    "prevención de incendios forestales", "brigada forestal", "clareo", "clareos forestales", 
    "raleo", "entresaca", "saca de madera", "carga de camión maderero", "desembosque", 
    "autocargador", "skidder", "camión maderero", "biomasa forestal", "astillado", "astilladora", 
    "biomasa", "leña de roble", "leña de encina", "leña de olivo", "leña de pino", 
    "leña de almendro", "venta de leña", "venta de pellets", "venta de astillas", 
    "retirada de restos forestales", "retirada de tocón", "destoconado", 
    "presupuesto trabajos forestales", "ingeniero forestal", "técnico forestal", 
    "autorización de tala", "peritaje forestal", "valoración de masa forestal", 
    "inventario forestal", "tasación de madera", "subasta de madera", "montes de utilidad pública", 
    "gestión de aprovechamientos micológicos", "gestión de pastos en monte", 
    "prevención de procesionaria", "tratamiento contra galeruca", "control de plagas forestales"
  ],
  transporte: [
    "transporte de ganado", "transporte vacuno", "transporte ovino", "transporte caprino", 
    "transporte porcino", "transporte equino", "transporte de caballos", "transporte de yeguas", 
    "transporte de aves", "transporte vivo", "camión ganadero", "remolque ganadero", 
    "jaula de transporte", "jaula ganadera", "transporte autorizado", "transporte sanitario", 
    "transporte de forraje", "transporte de paja", "transporte de heno", "transporte de alfalfa", 
    "transporte de pacas", "transporte de ensilado", "transporte de cereal", "transporte de grano", 
    "transporte de maquinaria agrícola", "transporte de tractor", "transporte de cosechadora", 
    "transporte de sembradora", "transporte de abonadora", "transporte especial", "góndola", 
    "plataforma extensible", "camión con grúa", "transporte de madera", "transporte de leña", 
    "transporte de estiércol", "transporte de purines", "cuba de purines", "cisterna transporte de agua", 
    "transporte de fitosanitarios", "agencia de transporte agropecuario", "ADR ganado", 
    "certificado de transporte de animales", "autoescuela transporte ganado", 
    "transporte nacional de ganado", "transporte internacional de ganado", "transporte España", 
    "transporte Portugal", "transporte Francia", "recogida granja", "entrega matadero", 
    "transporte a matadero", "camión cisterna leche", "transporte de leche", "transporte de huevos", 
    "transporte de colmenas", "transporte trashumancia", "transporte de abonos", 
    "transporte de fertilizantes", "transporte de pellet", "transporte de astillas", 
    "transporte refrigerado producto fresco"
  ],
  veterinarios: [
    "veterinario rural", "veterinario de grandes animales", "veterinario equino", "veterinario bovino", 
    "veterinario porcino", "veterinario ovino", "veterinario caprino", "veterinario de aves", 
    "veterinario apícola", "veterinario de explotación", "veterinario explotación lechera", 
    "veterinario de reproducción", "inseminación artificial", "inseminador", "inseminación de vacas", 
    "inseminación de ovejas", "inseminación de cerdas", "inseminación de yeguas", 
    "diagnóstico de gestación", "ecografía a vaca", "ecografía a yegua", "ecografía a oveja", 
    "sincronización de celos", "transferencia de embriones", "control reproductivo", "sanidad animal", 
    "programa vacunal", "vacunación de ganado", "desparasitación de ganado", "saneamiento ganadero", 
    "tuberculosis bovina", "brucelosis", "lengua azul", "ADV agrupación defensa sanitaria", "ADSG", 
    "identificación animal", "crotalado", "microchip", "pasaporte equino", "libro genealógico", 
    "calificador", "calificación racial", "podólogo bovino", "podología bovina", 
    "recorte funcional vacuno", "castración", "descornado", "autopsia", "cirugía equina", 
    "dentista equino", "fisioterapia equina", "urgencias veterinarias 24 horas", 
    "veterinario a domicilio", "presupuesto veterinario", "control oficial", 
    "prescripción veterinaria", "veterinario de pequeños rumiantes", "veterinario integrador porcino", 
    "veterinario de cebadero", "veterinario de fauna cinegética", "gestión sanitaria de explotación", 
    "plan sanitario", "registro de tratamientos", "recetas veterinarias"
  ],

  // ALIMENTOS KM0
  alimentos: [
    "alimentos km0", "productos km0", "producto local", "producto kilómetro cero", 
    "producto de proximidad", "producto de cercanía", "productos de huerta", "huevo campero", 
    "huevo ecológico", "huevo casero", "huevo de gallinas felices", "huevo de corral", 
    "miel del país", "miel artesanal", "miel ecológica", "queso artesanal", "queso de oveja", 
    "queso de cabra", "queso de vaca", "queso curado", "queso fresco", "queso payés", 
    "queso ahumado", "requesón", "cuajada", "mantequilla artesanal", "yogur de granja", 
    "leche cruda", "leche fresca", "leche de cabra", "leche de oveja", "carne de pasto", 
    "carne ecológica", "carne extensiva", "carne ibérica", "ternera autóctona", "ternera de pasto", 
    "ternera ecológica", "cordero lechal", "cordero pascual", "lechazo", "cabrito segureño", 
    "pollo de corral", "pollo campero", "conejo de granja", "embutido casero", "chorizo casero", 
    "morcilla casera", "longaniza", "butifarra", "sobrasada", "jamón ibérico", "jamón pata negra", 
    "jamón curado", "hortalizas ecológicas", "verdura ecológica", "tomate de huerto", 
    "lechuga ecológica", "patata local", "cebolla del país", "naranja de temporada", 
    "mandarina de temporada", "manzana autóctona", "manzana sidra", "fresa del país", 
    "frutos secos artesanos", "nuez del país", "almendra ecológica", "castaña del país", 
    "harina molida a piedra", "harina ecológica", "pan artesano", "pan masa madre", 
    "alubias del país", "lentejas de la Armuña", "garbanzos pedrosillanos", "judías del Barco", 
    "arroz local", "arroz Calasparra", "vino artesanal", "vino ecológico", "vino natural", 
    "vino del país", "sidra natural", "sidra del país", "cerveza artesana", "vermut artesano", 
    "aceite oliva virgen extra", "aceite oliva ecológico", "aceite de primera prensada", 
    "aceite primera cosecha", "AOVE ecológico", "AOVE temprano", "conservas artesanas", 
    "mermelada casera", "mermelada artesana", "conserva de pimientos", "conserva de tomate", 
    "gazpacho artesano", "salmorejo artesano", "espárrago de Navarra", "setas silvestres", 
    "micología", "trufa negra", "trufa del país", "caracoles", "productos ecológicos certificados", 
    "venta directa", "cesta de producto local", "mercado de agricultor", "mercado payés", 
    "venta directa del productor", "cooperativa local"
  ],

  // EQUIPOP
  "sillas de montar y accesorios": [ "silla de doma", "montura vaquera", "silla de salto", "silla uso general", "silla de raid", "silla western", "silla española", "silla portuguesa", "silla poni", "estribos de seguridad", "estribos vaqueros", "aciones de cuero", "aciones de nylon", "funda para silla", "protector de montura", "cincha anatómica", "cincha de doma", "cincha de salto", "baticola", "pechopetral", "silla de segunda mano", "montura usada", "montura a medida", "zalea", "borreguillo para silla" ],
  "mantillas y sudaderos": [ "mantilla de doma", "mantilla de salto", "mantilla uso general", "sudadero western", "sudadero vaquero", "salvacruces", "salvacruces de gel", "salvacruces de borreguillo", "mantilla personalizada", "mantilla con logo", "mantilla blanca", "mantilla de concurso", "sudadero transpirable", "sudadero anatómico", "mantilla de terciopelo", "pad western", "sudadero de neopreno", "mantilla de algodón" ],
  "cabezadas y riendas": [ "cabezada de doma", "cabezada de dar cuerda", "cabezada de cuadra", "cabezada de presentación", "cabezada western", "cabezada vaquera", "cabezada de salto", "riendas de cuero", "riendas de goma", "riendas de lona", "riendas alemanas", "riendas de atar", "hackamore", "filete articulado", "filete de anillas", "filete de oliva", "filete baucher", "filete pelham", "bocado vaquero", "bocado portugués", "bocado weymouth", "muserola alemana", "muserola sueca", "muserola cruzada", "muserola mexicana", "frontalera con brillos", "frontalera en v", "ahogadero", "montantes" ],
  "protectores y vendas": [ "protectores delanteros", "protectores traseros", "protectores de tendón", "protectores de menudillo", "protectores de cross", "campanas de goma", "campanas de neopreno", "campanas con borreguillo", "vendas de trabajo", "vendas de descanso", "vendas de polo", "bajo vendas", "protectores de transporte", "protectores de viaje", "rodilleras para caballo", "corvejeras", "protectores magnéticos", "protectores de gel" ],
  "mantas y ropa para caballos": [ "manta de invierno", "manta de exterior", "manta impermeable", "manta de cuadra", "manta de entretiempo", "manta de verano", "manta antimoscas", "manta de secado", "manta polar", "manta riñonera", "manta de transporte", "cubrecuellos", "cubrenucas", "máscara antimoscas", "orejeras antimoscas", "manta con cuello", "manta 200g", "manta 300g", "manta 400g" ],
  "cuidado e higiene del caballo": [ "cepillo de raíces", "cepillo suave", "bruza", "rasqueta de goma", "rasqueta metálica", "limpiacascos", "peine para crines", "esponja para caballo", "champú para caballos", "champú intensificador de color", "desenredante de crines", "brillo para el pelo", "grasa para cascos", "aceite para cascos", "alquitrán de pino", "ungüento para cascos", "repelente de moscas", "antimoscas natural", "crema cicatrizante", "arcilla refrescante", "gel frío", "toallitas húmedas" ],
  "alimentacion y suplementos": [ "pienso para caballos", "pienso de mantenimiento", "pienso de alta competición", "pienso para potros", "pienso para yeguas gestantes", "pienso senior", "pienso sin avena", "mash", "sal mineral", "piedra de sal", "electrolitos", "suplemento articular", "condroprotector", "biotina para cascos", "aceite de lino", "aceite de salmón", "ajo en polvo", "suplemento respiratorio", "suplemento digestivo", "probióticos", "premios para caballos", "snacks naturales", "golosinas equinas" ],
  "herrado y cascos": [ "botas para cascos", "botas de transición", "botas de enduro", "botas terapéuticas", "herraduras de hierro", "herraduras de aluminio", "herraduras ortopédicas", "clavos de herrar", "ramplones", "plantillas para cascos", "silicona para cascos", "resina reparadora", "escofina", "tenazas de herrador", "cuchilla de despalmar", "pujavante", "martillo de herrador", "yunque de herrador", "delantal de herrador" ],
  "trabajo pie a tierra y entrenamiento": [ "cuerda de dar cuerda", "cuerda de nudos", "ramal de algodón", "ramal de nylon", "ramal con cadena", "cabezada de nudos", "cabezada de parelli", "chambón", "gogue", "riendas de atar", "cinchuelo de dar cuerda", "pilar de enganche", "fusta de dar cuerda", "látigo de picadero", "conos de entrenamiento", "barras de tranqueo", "obstáculos de salto", "reparos de salto", "cavalettis" ],
  "transporte y viaje": [ "protectores de transporte altos", "protectores de transporte bajos", "vendas de transporte", "protector de cola", "bolsa para botas", "bolsa para casco", "bolsa para montura", "baúl de concurso", "armario de guadarnés portátil", "red para heno", "bolsa para heno", "comedero portátil", "bebedero portátil", "cámara para van", "cámara para camión", "espejo para remolque", "ataduras para remolque", "rampa de goma" ],
  "seguridad y visibilidad": [ "chaleco reflectante jinete", "manta reflectante caballo", "bandas reflectantes para patas", "pechopetral reflectante", "luces led para jinete", "luces led para estribos", "casco con luz", "brazalete reflectante", "funda de casco reflectante", "campanas reflectantes", "riendas reflectantes", "material de alta visibilidad" ],
  "equipamiento medico y recuperacion": [ "manta magnética", "protectores magnéticos", "campanas magnéticas", "botas de hielo", "botas de crioterapia", "manta de masaje", "aparato de masaje equino", "láser terapéutico", "botiquín de primeros auxilios", "vendas elásticas autoadherentes", "vetrap", "termómetro veterinario", "estetoscopio", "jeringas dosificadoras", "pasta desparasitante", "arcilla fría", "geles de calentamiento", "crema para rozaduras" ],
  "establo y cuadra": [ "bebedero automático", "bebedero de nivel constante", "comedero de esquina", "comedero de pared", "forrajera", "alfombra de goma para cuadra", "suelo de caucho", "viruta para caballos", "paja para cama", "pellets de madera", "horca para estiércol", "horca de plástico", "carretilla de dos ruedas", "escoba de raíces", "soporte para monturas", "soporte para cabezadas", "gancho porta bridas", "anilla de amarre", "cadena de amarre" ],
  "reproduccion y cria": [ "cabestro para potros", "manta para potros", "biberón para potros", "leche maternizada", "calostro en polvo", "test de ovulación", "cinturón de partos", "alarma de partos", "cámara de vigilancia cuadra", "suplementos para yeguas gestantes", "suplementos para sementales", "ecógrafo veterinario", "material de inseminación", "termómetro basal" ],
  "otros productos para caballos": [ "libros ecuestres", "revistas de caballos", "decoración ecuestre", "cuadros de caballos", "esculturas de caballos", "joyas con crines", "pulseras de crin", "regalos para caballistas", "artesanía ecuestre", "artículos de coleccionismo", "antigüedades ecuestres" ],
  "calzado ecuestre": [ "botas de montar altas", "botas de doma", "botas de salto", "botas de campo", "botas jodhpur", "botines de montar", "botines con cremallera", "botines con elástico", "botas western", "botas camperas", "botas de establo", "botas de invierno térmicas", "botas de goma", "polainas de cuero", "polainas de neopreno", "polainas sintéticas", "calcetines de equitación", "calcetines de rombos", "hormas para botas", "saca botas", "limpiabotas", "grasa para cuero" ],
  "cascos y seguridad": [ "casco de equitación", "casco de doma", "casco de salto", "casco de cross", "casco western", "casco regulable", "casco de terciopelo", "casco mate", "casco con brillos", "chaleco protector", "chaleco de seguridad nivel 3", "chaleco articulado", "protector de espalda", "tortuga protectora", "chaleco airbag", "airbag ecuestre", "bombonas CO2 para airbag", "funda para casco", "mochila para casco", "red para el pelo" ],
  "ropa ecuestre mujer": [ "pantalón de montar mujer", "pantalón con culera de silicona", "pantalón con culera de cuero", "pantalón de montar blanco", "leggings de equitación", "mallas de montar", "camisa de concurso mujer", "polo de equitación mujer", "camiseta técnica mujer", "chaqueta de concurso mujer", "frac de doma mujer", "sudadera ecuestre", "forro polar mujer", "chaleco acolchado mujer", "abrigo largo de montar", "impermeable transparente", "cinturón de equitación" ],
  "ropa ecuestre hombre": [ "pantalón de montar hombre", "pantalón con rodilleras de silicona", "pantalón de montar blanco hombre", "camisa de concurso hombre", "polo de equitación hombre", "camiseta transpirable", "chaqueta de concurso hombre", "frac de doma hombre", "sudadera ecuestre hombre", "forro polar hombre", "chaleco acolchado hombre", "chaqueta impermeable hombre", "abrigo de equitación", "cinturón de cuero", "corbata de concurso" ],
  "ropa ecuestre infantil": [ "pantalón de montar niño", "pantalón de montar niña", "leggings ecuestres niña", "pantalón blanco infantil", "polo de equitación infantil", "camisa de concurso niña", "chaqueta de concurso infantil", "sudadera con caballos", "chaleco infantil", "casco de montar niño", "botas de goma infantiles", "botines infantiles", "polainas para niños", "guantes infantiles", "fusta infantil con diseño" ],
  "guantes ecuestres": [ "guantes de montar blancos", "guantes de concurso", "guantes de cuero", "guantes sintéticos", "guantes de verano", "guantes transpirables", "guantes de invierno", "guantes térmicos", "guantes impermeables", "guantes con agarre", "guantes para dar cuerda" ],
  "ropa reflectante y seguridad vial": [ "chaleco reflectante jinete", "bandas reflectantes", "equipamiento led", "accesorios de visibilidad", "luces para botas", "luces para casco", "chaqueta de alta visibilidad" ],
  "fustas espuelas y ayudas": [ "fusta de doma", "fusta de salto", "fusta de uso general", "fusta corta", "fusta estándar", "tralla", "látigo", "espuelas de doma", "espuelas de contacto", "espuelas de ruleta", "espuelas gallo largo", "espuelas de plástico", "espuelas western", "correas de espuela de cuero", "correas de nylon", "protectores de espuelas" ],
  "accesorios para riders": [ "mochila de concurso", "bolsa de aseo", "riñonera para montar", "porta móviles para pierna", "gorra ecuestre", "sombrero western", "sombrero cordobés", "gorro de invierno", "bufanda braga", "cinturón con bocado", "pulsera ecuestre", "colgante herradura", "llavero caballo", "taza ecuestre", "botella térmica" ],
  "equipamiento de competicion": [ "frac de competición", "chaqueta de concurso", "camisa de concurso", "polo blanco", "plastrón", "corbata de concurso", "pantalón blanco", "guantes blancos", "red para moño", "coletero con lazo", "adorno para moño", "porta números", "números para cabezada", "números para sudadero", "carpeta para pasaporte", "portadocumentos equino" ],
  "outdoor y lifestyle ecuestre": [ "chaqueta softshell", "abrigo impermeable", "abrigo largo para montar", "pantalón de invierno", "mono de trabajo", "ropa térmica jinete", "calcetines térmicos", "botas de campo lifestyle", "zapatos náuticos", "jersey de lana", "chaqueta tweed", "ropa estilo country" ],
  "bolsas y almacenamiento": [ "bolsa para botas", "bolsa para casco", "maletas ecuestres", "organizadores de cuadra", "mochilas técnicas", "bolsa de aseo equino", "baúl para monturas", "funda para silla de doma", "funda porta traje" ],
  "otros productos para riders": [ "vintage ecuestre jinete", "artesanía jinete", "decoración jinete", "coleccionismo jinete", "libros de equitación", "manuales de doma" ]
};
