export async function GET() {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.ruralpop.com';
    
    // We statically define the two chunks we know are generated by sitemap.ts
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>${baseUrl}/sitemap_0.xml</loc>
    </sitemap>
    <sitemap>
        <loc>${baseUrl}/sitemap_1.xml</loc>
    </sitemap>
    <sitemap>
        <loc>${baseUrl}/sitemap_anuncios.xml</loc>
    </sitemap>

    <sitemap>
        <loc>${baseUrl}/sitemap_lonjas.xml</loc>
    </sitemap>
</sitemapindex>`.trim();

    return new Response(xml, {
        headers: {
            'Content-Type': 'application/xml',
            // short cache to be safe
            'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate',
        },
    });
}
