import type { MetadataRoute } from 'next';
import { CATEGORIES } from '@/constants/categories';
import { LOCATIONS } from '@/constants/locations';
import { buildSeoUrl } from '@/utils/seoUtils';
import { SEO_LANDINGS } from '@/constants/seoLandings';
import { createClient } from '@/utils/supabase/server';

import autogeneratedSeoTerms from '@/constants/autogeneratedSeoTerms.json';

export const dynamic = "force-dynamic";

export async function getSitemapXmlById(id: number): Promise<string> {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.ruralpop.com';

    // Parse ID safely
    const parsedId = Number(id) || 0;

    const sitemapEntries: any[] = [];

    const addEntry = (path: string, priority: number = 0.8) => {
        sitemapEntries.push({
            url: `${baseUrl}${path}`,
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority,
        });
    };

    // 0. Fetch all active listings to local memory cache for ultra-fast threshold counting (Anti Thin-Content)
    const supabase = await createClient();
    let listingCache: any[] = [];
    let fetchPage = 0;
    while(true) {
        const { data } = await supabase
            .from('listings')
            .select('category, subcategory, province_id, title, description')
            .eq('status', 'active')
            .range(fetchPage * 1000, (fetchPage + 1) * 1000 - 1);
            
        if (!data || data.length === 0) break;
        listingCache = listingCache.concat(data);
        if (data.length < 1000) break;
        fetchPage++;
    }

    const hasEnoughListings = (cat?: string, sub?: string, prov?: string, q?: string) => {
        let count = 0;
        for (const l of listingCache) {
            let match = true;
            if (cat && l.category !== cat) match = false;
            if (match && sub && l.subcategory?.toLowerCase() !== sub.toLowerCase()) match = false;
            if (match && prov && l.province_id !== prov) match = false;
            if (match && q) {
                const raw = `${l.title} ${l.description || ""}`.toLowerCase();
                const terms = q.toLowerCase().split(/[\s\-]+/).filter(t => t.length > 2);
                for (const t of terms) {
                    if (!raw.includes(t)) {
                        match = false;
                        break;
                    }
                }
            }
            if (match) count++;
            if (count >= 8) return true; // Optimization: early exit
        }
        return false;
    };

    // 1. Home Base
    addEntry('/', 1.0);

    // 1.5 Landings SEO Long-Tail (Alta prioridad)
    SEO_LANDINGS.forEach(landing => {
        const provId = landing.province ? LOCATIONS.find(l => l.name === landing.province)?.id : undefined;
        if (hasEnoughListings(landing.category, landing.subcategory, provId, landing.searchQuery)) {
            addEntry(`/s/${landing.slug}`, 0.95);
        }
    });

    // 2. Solo Categorías y Subcategorías
    CATEGORIES.forEach(cat => {
        if (hasEnoughListings(cat.id)) addEntry(buildSeoUrl({ category: cat.id }), 0.9);

        cat.subcategories.forEach(sub => {
            if (hasEnoughListings(cat.id, sub)) addEntry(buildSeoUrl({ category: cat.id, subcategory: sub }), 0.8);
        });
    });

    // 3. Solo Localizaciones
    LOCATIONS.forEach(loc => {
        if (hasEnoughListings(undefined, undefined, loc.id)) addEntry(buildSeoUrl({ province_id: loc.id }), 0.8);
    });

    // 4. Combinaciones: Categoría + Localización
    CATEGORIES.forEach(cat => {
        LOCATIONS.forEach(loc => {
            if (hasEnoughListings(cat.id, undefined, loc.id)) {
                addEntry(buildSeoUrl({ category: cat.id, province_id: loc.id }), 0.7);
            }
        });
    });

    // 5. Combinaciones: Subcategoría + Localización
    CATEGORIES.forEach(cat => {
        cat.subcategories.forEach(sub => {
            LOCATIONS.forEach(loc => {
                if (hasEnoughListings(cat.id, sub, loc.id)) {
                    addEntry(buildSeoUrl({ category: cat.id, subcategory: sub, province_id: loc.id }), 0.6);
                }
            });
        });
    });

    // 5.5 Términos de búsqueda populares y directos hardcodeados
    const POPULAR_SEARCHES = [
        "vaca", "toro", "ternero",
        "caballo", "yegua", "potro",
        "cabra", "oveja", "cordero",
        "cerdo", "gallina", "perro",
        "tractor", "remolque", "cosechadora", 
        "empacadora", "desbrozadora", "arado",
        "sembradora", "abonadora",
        "paja", "alfalfa", "avena", "cebada", "maiz"
    ];

    POPULAR_SEARCHES.forEach(term => {
        if (hasEnoughListings(undefined, undefined, undefined, term)) addEntry(buildSeoUrl({ q: term }), 0.85);
    });

    // 5.6 Auto-Generated Data-Driven Long Tail SEO (30.000+ Permutaciones)
    if (Array.isArray(autogeneratedSeoTerms)) {
        autogeneratedSeoTerms.forEach((term: string) => {
            if (!POPULAR_SEARCHES.includes(term)) {
                if (hasEnoughListings(undefined, undefined, undefined, term)) addEntry(buildSeoUrl({ q: term }), 0.80);
            }
            LOCATIONS.forEach(loc => {
                if (hasEnoughListings(undefined, undefined, loc.id, term)) {
                    addEntry(buildSeoUrl({ q: term, province_id: loc.id }), 0.50);
                }
            });
        });
    }

    // 6. Magazine
    addEntry('/magazine', 0.9);

    const { data: posts } = await supabase
        .from('magazine_posts')
        .select('slug, updated_at, published_at')
        .eq('is_published', true);

    if (posts) {
        posts.forEach((post: { slug: string; updated_at: string | null; published_at: string | null }) => {
            sitemapEntries.push({
                url: `${baseUrl}/magazine/${post.slug}`,
                lastModified: new Date(post.updated_at || post.published_at || new Date().toISOString()),
                changeFrequency: 'weekly',
                priority: 0.8,
            });
        });
    }

    // Dividimos en bloques de máximo 40.000 para cumplir holgadamente con el límite de 50.000 de Google
    const SLICE_SIZE = 40000;
    const start = parsedId * SLICE_SIZE;
    const end = start + SLICE_SIZE;

    const slice = sitemapEntries.slice(start, end);

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    slice.forEach(entry => {
        xml += `  <url>\n`;
        xml += `    <loc>${entry.url}</loc>\n`;
        xml += `    <lastmod>${entry.lastModified.toISOString()}</lastmod>\n`;
        xml += `    <changefreq>${entry.changeFrequency}</changefreq>\n`;
        xml += `    <priority>${entry.priority}</priority>\n`;
        xml += `  </url>\n`;
    });

    xml += `</urlset>`;

    return xml;
}
