import type { MetadataRoute } from 'next';
import { CATEGORIES } from '@/constants/categories';
import { LOCATIONS } from '@/constants/locations';
import { buildSeoUrl } from '@/utils/seoUtils';
import { SEO_LANDINGS } from '@/constants/seoLandings';
import { createClient } from '@/utils/supabase/server';

import autogeneratedSeoTerms from '@/constants/autogeneratedSeoTerms.json';

export const dynamic = "force-dynamic";

export async function getSitemapXmlById(id: number): Promise<string> {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.ruralpop.com';

    // Parse ID safely
    const parsedId = Number(id) || 0;

    const sitemapEntries: any[] = [];

    const addEntry = (path: string, priority: number = 0.8) => {
        sitemapEntries.push({
            url: `${baseUrl}${path}`,
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority,
        });
    };

    // 1. Home Base
    addEntry('/', 1.0);

    // 1.5 Landings SEO Long-Tail (Alta prioridad)
    SEO_LANDINGS.forEach(landing => {
        addEntry(`/s/${landing.slug}`, 0.95);
    });

    // 2. Solo Categorías y Subcategorías
    CATEGORIES.forEach(cat => {
        // Categoría sola
        addEntry(buildSeoUrl({ category: cat.id }), 0.9);

        // Subcategorías solas
        cat.subcategories.forEach(sub => {
            addEntry(buildSeoUrl({ category: cat.id, subcategory: sub }), 0.8);
        });
    });

    // 3. Solo Localizaciones
    LOCATIONS.forEach(loc => {
        addEntry(buildSeoUrl({ province_id: loc.id }), 0.8);
    });

    // 4. Combinaciones: Categoría + Localización
    CATEGORIES.forEach(cat => {
        LOCATIONS.forEach(loc => {
            addEntry(buildSeoUrl({ category: cat.id, province_id: loc.id }), 0.7);
        });
    });

    // 5. Combinaciones: Subcategoría + Localización
    CATEGORIES.forEach(cat => {
        cat.subcategories.forEach(sub => {
            LOCATIONS.forEach(loc => {
                addEntry(buildSeoUrl({ category: cat.id, subcategory: sub, province_id: loc.id }), 0.6);
            });
        });
    });

    // 5.5 Términos de búsqueda populares y directos hardcodeados
    const POPULAR_SEARCHES = [
        "vaca", "toro", "ternero",
        "caballo", "yegua", "potro",
        "cabra", "oveja", "cordero",
        "cerdo", "gallina", "perro",
        "tractor", "remolque", "cosechadora", 
        "empacadora", "desbrozadora", "arado",
        "sembradora", "abonadora",
        "paja", "alfalfa", "avena", "cebada", "maiz"
    ];

    POPULAR_SEARCHES.forEach(term => {
        addEntry(buildSeoUrl({ q: term }), 0.85);
    });

    // 5.6 Auto-Generated Data-Driven Long Tail SEO (30.000+ Permutaciones)
    if (Array.isArray(autogeneratedSeoTerms)) {
        autogeneratedSeoTerms.forEach((term: string) => {
            if (!POPULAR_SEARCHES.includes(term)) {
                addEntry(buildSeoUrl({ q: term }), 0.80);
            }
            LOCATIONS.forEach(loc => {
                addEntry(buildSeoUrl({ q: term, province_id: loc.id }), 0.50);
            });
        });
    }

    // 6. Magazine
    addEntry('/magazine', 0.9);

    const supabase = await createClient();
    const { data: posts } = await supabase
        .from('magazine_posts')
        .select('slug, updated_at, published_at')
        .eq('is_published', true);

    if (posts) {
        posts.forEach((post: { slug: string; updated_at: string | null; published_at: string | null }) => {
            sitemapEntries.push({
                url: `${baseUrl}/magazine/${post.slug}`,
                lastModified: new Date(post.updated_at || post.published_at || new Date().toISOString()),
                changeFrequency: 'weekly',
                priority: 0.8,
            });
        });
    }

    // Dividimos en bloques de máximo 40.000 para cumplir holgadamente con el límite de 50.000 de Google
    const SLICE_SIZE = 40000;
    const start = parsedId * SLICE_SIZE;
    const end = start + SLICE_SIZE;

    const slice = sitemapEntries.slice(start, end);

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    slice.forEach(entry => {
        xml += `  <url>\n`;
        xml += `    <loc>${entry.url}</loc>\n`;
        xml += `    <lastmod>${entry.lastModified.toISOString()}</lastmod>\n`;
        xml += `    <changefreq>${entry.changeFrequency}</changefreq>\n`;
        xml += `    <priority>${entry.priority}</priority>\n`;
        xml += `  </url>\n`;
    });

    xml += `</urlset>`;

    return xml;
}
