import type { MetadataRoute } from 'next';
import { CATEGORIES } from '@/constants/categories';
import { LOCATIONS } from '@/constants/locations';
import { buildSeoUrl } from '@/utils/seoUtils';
import { SEO_LANDINGS } from '@/constants/seoLandings';
import { SEO_LANDINGS_PT } from '@/constants/seoLandingsPt';
import { createClient } from '@/utils/supabase/server';

import autogeneratedSeoTerms from '@/constants/autogeneratedSeoTerms.json';

export const dynamic = "force-dynamic";

export async function getSitemapXmlById(id: number, locale: 'es' | 'pt' = 'es', domainOverride?: string): Promise<string> {
    const isPtLocale = locale === 'pt';
    const baseUrl = domainOverride || (isPtLocale ? 'https://www.ruralpop.pt' : (process.env.NEXT_PUBLIC_SITE_URL || 'https://www.ruralpop.com'));
    const isDomainPt = baseUrl.includes('ruralpop.pt');
    const pathPrefix = (isPtLocale && !isDomainPt) ? '/pt' : '';

    // Parse ID safely
    const parsedId = Number(id) || 0;

    interface SitemapEntry {
        url: string;
        lastModified: Date;
        changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
        priority: number;
    }

    const sitemapEntries: SitemapEntry[] = [];

    const addEntry = (path: string, priority: number = 0.8, changeFrequency: SitemapEntry['changeFrequency'] = 'daily') => {
        let cleanPath = path.startsWith('/') ? path : `/${path}`;
        if (isDomainPt && (cleanPath === '/pt' || cleanPath.startsWith('/pt/'))) {
            cleanPath = cleanPath.replace(/^\/pt/, '') || '/';
        }
        const fullUrl = isDomainPt 
            ? `${baseUrl}${cleanPath === '/' ? '' : cleanPath}`
            : `${baseUrl}${pathPrefix}${cleanPath}`;

        sitemapEntries.push({
            url: fullUrl || baseUrl,
            lastModified: new Date(),
            changeFrequency,
            priority,
        });
    };

    // 1. Home Base & Páginas Institucionales Clave
    addEntry('/', 1.0);
    addEntry('/contact', 0.8, 'monthly');
    addEntry(isPtLocale ? '/perguntas-frequentes' : '/preguntas-frecuentes', 0.8, 'weekly');

    // 1.5 Landings SEO Long-Tail (Alta prioridad)
    const landingsToUse = locale === 'pt' ? SEO_LANDINGS_PT : SEO_LANDINGS;
    landingsToUse.forEach(landing => {
        addEntry(`/s/${landing.slug}`, 0.95);
    });

    const RURALPOP_CATEGORIES = CATEGORIES.filter(cat => 
        ['ganaderia', 'maquinaria', 'forraje', 'fincas', 'agricultura', 'servicios', 'alimentos'].includes(cat.id)
    );

    // 2. Solo Categorías y Subcategorías
    RURALPOP_CATEGORIES.forEach(cat => {
        // Categoría sola
        addEntry(buildSeoUrl({ category: cat.id }, locale, isDomainPt), 0.9);

        // Subcategorías solas
        cat.subcategories.forEach(sub => {
            addEntry(buildSeoUrl({ category: cat.id, subcategory: sub }, locale, isDomainPt), 0.8);
        });
    });

    // Filter locations by locale
    const validLocations = LOCATIONS.filter(loc => {
        if (loc.type === 'community') return !isPtLocale;
        const isPtLoc = !isNaN(Number(loc.id)) && Number(loc.id) >= 100;
        return isPtLocale ? isPtLoc : (!isPtLoc);
    });

    // 3. Solo Localizaciones
    validLocations.forEach(loc => {
        addEntry(buildSeoUrl({ province_id: loc.id }, locale, isDomainPt), 0.8);
    });

    // 4. Combinaciones: Categoría + Localización
    RURALPOP_CATEGORIES.forEach(cat => {
        validLocations.forEach(loc => {
            addEntry(buildSeoUrl({ category: cat.id, province_id: loc.id }, locale, isDomainPt), 0.7);
        });
    });

    // 5. Combinaciones: Subcategoría + Localización
    RURALPOP_CATEGORIES.forEach(cat => {
        cat.subcategories.forEach(sub => {
            validLocations.forEach(loc => {
                addEntry(buildSeoUrl({ category: cat.id, subcategory: sub, province_id: loc.id }, locale, isDomainPt), 0.6);
            });
        });
    });

    // 5.5 Términos de búsqueda populares y directos hardcodeados
    const POPULAR_SEARCHES = [
        "vaca", "toro", "ternero",
        "caballo", "yegua", "potro",
        "cabra", "oveja", "cordero",
        "cerdo", "gallina", "perro",
        "tractor", "remolque", "cosechadora", 
        "empacadora", "desbrozadora", "arado",
        "sembradora", "abonadora",
        "paja", "alfalfa", "avena", "cebada", "maiz"
    ];

    POPULAR_SEARCHES.forEach(term => {
        addEntry(buildSeoUrl({ q: term }, locale, isDomainPt), 0.85);
    });

    // 5.6 Auto-Generated Data-Driven Long Tail SEO (30.000+ Permutaciones)
    if (Array.isArray(autogeneratedSeoTerms)) {
        autogeneratedSeoTerms.forEach((term: string) => {
            if (!POPULAR_SEARCHES.includes(term)) {
                addEntry(buildSeoUrl({ q: term }, locale, isDomainPt), 0.80);
            }
            validLocations.forEach(loc => {
                addEntry(buildSeoUrl({ q: term, province_id: loc.id }, locale, isDomainPt), 0.50);
            });
        });
    }

    // 6. Magazine (Exclusivo para España)
    if (!isPtLocale) {
        addEntry('/magazine', 0.9);

        const supabase = await createClient();
        const { data: posts } = await supabase
            .from('magazine_posts')
            .select('slug, updated_at, published_at')
            .eq('is_published', true);

        if (posts) {
            posts.forEach((post: { slug: string; updated_at: string | null; published_at: string | null }) => {
                sitemapEntries.push({
                    url: `${baseUrl}/magazine/${post.slug}`,
                    lastModified: new Date(post.updated_at || post.published_at || new Date().toISOString()),
                    changeFrequency: 'weekly',
                    priority: 0.8,
                });
            });
        }
    }

    // Dividimos en bloques de máximo 40.000 para cumplir holgadamente con el límite de 50.000 de Google
    const SLICE_SIZE = 40000;
    const start = parsedId * SLICE_SIZE;
    const end = start + SLICE_SIZE;

    const slice = sitemapEntries.slice(start, end);

    // Si el slice está completamente vacío (ej. sitemap_4), metemos la portada como fallback
    // para evitar que Google Search Console nos lance un error de "Sitemap vacío" o XML inválido
    if (slice.length === 0) {
        slice.push({
            url: baseUrl,
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 1.0,
        });
    }

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    slice.forEach(entry => {
        xml += `  <url>\n`;
        xml += `    <loc>${entry.url}</loc>\n`;
        xml += `    <lastmod>${entry.lastModified.toISOString()}</lastmod>\n`;
        xml += `    <changefreq>${entry.changeFrequency}</changefreq>\n`;
        xml += `    <priority>${entry.priority}</priority>\n`;
        xml += `  </url>\n`;
    });

    xml += `</urlset>`;

    return xml;
}

/**
 * Memory / Decisiones Técnicas:
 * - Se añade `/contact` y `/preguntas-frecuentes` explícitamente en el sitemap de Ruralpop
 *   para acelerar la indexación directa por Google y evitar que los usuarios lleguen a URLs
 *   del tenant secundario (Equipop) al buscar soporte o contacto de Ruralpop.
 * - Tipado estricto `SitemapEntry` para eliminar el uso de `any[]`.
 */
