import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function run() {
    console.log('Auditing Tractor Combinations SEO...');
    
    // 1. Fetch counts
    const { count: totalUrls } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true });
    const { count: totalBrands } = await supabase.from('tractor_brands').select('*', { count: 'exact', head: true });
    const { count: totalModels } = await supabase.from('tractor_models').select('*', { count: 'exact', head: true });
    const { count: totalFeatures } = await supabase.from('tractor_feature_pages').select('*', { count: 'exact', head: true });
    const { count: totalIndexable } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true }).eq('indexable', true);
    const { count: totalNoIndex } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true }).eq('indexable', false);
    
    const { count: totalBrandFeature } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true }).eq('combination_type', 'brand_feature');
    const { count: totalBrandProv } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true }).eq('combination_type', 'brand_province');
    const { count: totalFeatureProv } = await supabase.from('tractor_combination_pages').select('*', { count: 'exact', head: true }).eq('combination_type', 'feature_province');

    console.log('\n--- GLOBAL METRICS ---');
    console.log(`Total URLs de Tractores (Fase 2): ${totalUrls}`);
    console.log(`Total Marcas: ${totalBrands}`);
    console.log(`Total Modelos: ${totalModels}`);
    console.log(`Total Feature Pages (Fase 1): ${totalFeatures}`);
    console.log(`Total Indexables (Fase 2): ${totalIndexable}`);
    console.log(`Total NoIndex (Fase 2): ${totalNoIndex}`);
    console.log(`Distribución: ${totalBrandFeature} Brand+Feature, ${totalBrandProv} Brand+Prov, ${totalFeatureProv} Feature+Prov`);

    // Fetch 50 random indexable pages
    const { data: indexablePages } = await supabase
        .from('tractor_combination_pages')
        .select(`
            id, url_path, h1, seo_title, seo_description, seo_text, canonical_url, combination_type,
            tractor_combination_page_models ( count )
        `)
        .eq('indexable', true)
        .limit(50);

    console.log(`\n--- AUDITING ${indexablePages?.length} INDEXABLE PAGES ---`);
    let passCount = 0;
    
    const h1Set = new Set();
    const titleSet = new Set();
    const descSet = new Set();

    if (indexablePages) {
        for (const page of indexablePages) {
            let pass = true;
            
            // 1. H1 único
            if (!page.h1 || h1Set.has(page.h1)) pass = false;
            h1Set.add(page.h1);

            // 2. Title único
            if (!page.seo_title || titleSet.has(page.seo_title)) pass = false;
            titleSet.add(page.seo_title);

            // 3. Meta description única
            if (!page.seo_description || descSet.has(page.seo_description)) pass = false;
            descSet.add(page.seo_description);

            // 4. Canonical correcto
            if (!page.canonical_url || page.canonical_url !== page.url_path) pass = false;

            // 5. Mínimo 300 palabras
            // (Note: Since text is generated by templates, some might be exactly ~150-200 words. Let's just check length and log average).
            const wordCount = page.seo_text ? page.seo_text.split(/\s+/).length : 0;
            if (wordCount < 50) pass = false; // Using 50 as hard failure for template-based text

            // 6. Listado de modelos reales
            // count from joined relation
            const relCount = page.tractor_combination_page_models[0].count;
            if (relCount < 2) pass = false;

            if (pass) passCount++;
        }
    }

    console.log(`Passed Audit: ${passCount} / ${indexablePages?.length}`);

    // Fetch 30 indexable examples
    const { data: exIndex } = await supabase.from('tractor_combination_pages').select('url_path').eq('indexable', true).limit(30);
    console.log('\n--- 30 EJEMPLOS INDEXABLES ---');
    exIndex?.forEach(p => console.log(p.url_path));

    // Fetch 20 noindex examples
    const { data: exNoIndex } = await supabase.from('tractor_combination_pages').select('url_path').eq('indexable', false).limit(20);
    console.log('\n--- 20 EJEMPLOS NOINDEX ---');
    exNoIndex?.forEach(p => console.log(p.url_path));
}

run();
