import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

dotenv.config({ path: join(dirname(fileURLToPath(import.meta.url)), '../.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://zrpucbuvojskcwrhwevv.supabase.co';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseKey) { throw new Error('NO KEY'); }

const db = createClient(supabaseUrl, supabaseKey);

// Amplia lista de palabras vacías, preposiciones, verbos no útiles y medidas
const stopWords = new Set([
  'de', 'la', 'el', 'en', 'y', 'a', 'los', 'del', 'las', 'un', 'una', 'con', 
  'para', 'por', 'se', 'su', 'al', 'es', 'o', 'como', 'más', 'pero', 'sus', 
  'le', 'ya', 'o', 'muy', 'sin', 'sobre', 'este', 'me', 'hasta', 'hay', 'donde', 
  'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra',
  'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos',
  'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos',
  'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas',
  'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas',
  'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo',
  'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra',
  'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos',
  'esas', 'aquel', 'aquella', 'aquellos', 'aquellas', 'esto', 'eso', 'aquello',
  'gran', 'vendo', 'venta', 'compro', 'compra', 'se', 'vende', 'compran', 'venden',
  'buen', 'buena', 'estado', 'ano', 'anos', 'meses', 'dias', 'horas', 'kilos', 'litros',
  'cm', 'mm', 'kg', 'cv', 'hp', 'tlf', 'whatsapp', 'precio', 'barato', 'urgente',
  'cambio', 'intercambio', 'regalo', 'adopcion', 'marca', 'modelo', 'gratis',
  'oferta', 'ocasion', 'oportunidad', 'excelente', 'perfecto', 'nuevos', 'nuevas',
  'nuevo', 'nueva', 'usado', 'usada', 'usados', 'usadas', 'segunda', 'mano',
  'lote', 'conjunto', 'pareja', 'macho', 'hembra', 'machos', 'hembras', 'color',
  'tipo', 'tienen', 'tiene', 'hola', 'solo', 'urge'
]);

// Normaliza limpiando acentos y puntuación, y pasa a minúsculas
function normalize(str) {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9\s]/g, ' ').trim();
}

async function run() {
  console.log("Fetching active listings to build SEO Keyword map...");
  let allTitles = [];
  let from = 0;
  const size = 1000;
  let hasMore = true;

  while (hasMore) {
    const { data, error } = await db.from('listings').select('title, status').eq('status', 'active').range(from, from + size - 1);
    if (error) {
      console.error(error);
      break;
    }
    if (data.length > 0) {
      allTitles.push(...data);
      from += size;
    } else {
      hasMore = false;
    }
  }

  console.log(`Fetched ${allTitles.length} active listings.`);

  const nGramsCounts = new Map();

  function addNGram(ngram) {
    if (ngram.length <= 3) return; // ignora palabras de 3 letas o menos tipo "las", "dos"
    if (/^\d+$/.test(ngram)) return; // no puros números
    if (stopWords.has(ngram)) return; 

    // Revisar guiones (multi-words)
    const words = ngram.split('-');
    if (words.length > 1) {
        // Fallbacks adicionales: que no acabe o empiece en stop word ("vaca-en")
        if (stopWords.has(words[0]) || stopWords.has(words[words.length - 1])) return;
        // Que no tenga números
        if (words.some(w => /^\d+$/.test(w))) return;
    }

    nGramsCounts.set(ngram, (nGramsCounts.get(ngram) || 0) + 1);
  }

  allTitles.forEach(listing => {
    const title = normalize(listing.title);
    const words = title.split(/\s+/).filter(w => w.length > 0 && !stopWords.has(w));

    // 1-grams
    words.forEach(w => addNGram(w));

    // 2-grams
    for (let i = 0; i < words.length - 1; i++) {
        addNGram(`${words[i]}-${words[i+1]}`);
    }

    // 3-grams
    for (let i = 0; i < words.length - 2; i++) {
        addNGram(`${words[i]}-${words[i+1]}-${words[i+2]}`);
    }
  });

  // Exportar los que salen 2 o más veces
  const validTerms = Array.from(nGramsCounts.entries())
    .filter(([ngram, count]) => count >= 2)
    .sort((a, b) => b[1] - a[1])
    .map(([ngram]) => ngram);

  console.log(`Total valid unique keyword searches extracted: ${validTerms.length}`);

  const targetPath = join(dirname(fileURLToPath(import.meta.url)), '../src/constants/autogeneratedSeoTerms.json');
  fs.writeFileSync(targetPath, JSON.stringify(validTerms, null, 2));

  console.log(`Successfully wrote ${validTerms.length} keywords to ${targetPath}`);
}

run();
